### ISSUE TITLE
Unraid

### ISSUE THREAD

**Issue by HappyNows** [MitchTalmadge/AMP-dockerized#104]
Does this container work in unraid? As far as I can tell it simply won't let me use the same port that the game is using, since unraid only lets you use one port per container.

**Comment by MitchTalmadge** [comment]
Yes, many people use it with Unraid. I personally have never used Unraid, but someone made a support thread for it: https://forums.unraid.net/topic/98290-support-amp-application-management-panel-corneliousjd-repo/

**Comment by judsonjames** [comment]
I'm using this container in UnRAID, and you can open as many ports as needed for a container. You just specify a port range that you want to allow exposed, as you would in a Dockerfile or Docker Compose. The one catch is you have to make sure you're port forwarding on your router the only ports that you are actually using.

![image](https://user-images.githubusercontent.com/16809002/144531866-820bc28d-717c-4653-abf3-369849b0a30b.png)

**Comment by Joly0** [comment]
Can confirm, this container works perfectly fine with unraid and as shown above it ls simple to add/open more ports
