### ISSUE TITLE
"Triton" Update and Minecraft 1.18

### ISSUE THREAD

**Issue by judsonjames** [MitchTalmadge/AMP-dockerized#105]
Minecraft 1.18 dropped, and CubeCoders put out an update (Triton) that specifically adds support for Java17 in their UI.

https://support.cubecoders.com/thread/amp-2-3-triton-release-notes/

However, when I pulled the latest container from Docker Hub earlier today, Java17 wasn't in the container and I'm unable to install it from the Docker shell. Attached is a screenshot of me manually updating from within the web app and being unable to select Java17 from the dropdown.
![image](https://user-images.githubusercontent.com/16809002/144532343-af05645f-8aa6-4532-b78a-b1cca4478397.png)

And I see in the Dockerfile you're installing Java17, but it isn't showing up in my latest pull via UnRAID. 
https://github.com/MitchTalmadge/AMP-dockerized/blob/c3779b9bfb38423b98abe458b9e486303a5881a4/Dockerfile#L129

Should I try re-pulling the container and trying again? Or is there some additional steps I can do to install to the container manually?

**Comment by MitchTalmadge** [comment]
It's weird that you still have 16 but don't have 17. It seems like the new image did not get applied to your container for some reason. I don't use UnRAID but my usual strategy with docker-compose is:
1. `docker-compose down`
2. `docker-compose pull`
3. `docker-compose up -d` (`-d` for detached)

So I would wonder if you need to bring the UnRAID container "down" somehow, pull, and bring it back up. I wish I had more experience with UnRAID to help you

**Comment by MitchTalmadge** [comment]
Just to be certain, I updated to the latest image on my own AMP and I am seeing Java 17 and AMP version 2.3.0.6:

![image](https://user-images.githubusercontent.com/8848080/144558333-98c98742-1d93-4dc4-9833-1b0b2e33f53d.png)

![image](https://user-images.githubusercontent.com/8848080/144558344-f4fa2013-e6ca-43c1-b8f2-ce54b3898181.png)

**Comment by judsonjames** [comment]
I tried Docker Compose on my local Linux station as mentioned above and resolved it. But UnRAID just uses standard Docker management

What I ended up doing is pulling the container manually from the CLI on my UnRAID host and force pull the latest image you built. After doing that I was able to update my AMP image to the latest version and am now getting the option for Java 17.

However, after doing some further research for a more user friendly way of doing it in UnRAID there's actually a `Check Updates` button on the Docker page. To test it I rolled back my Docker image in the CLI and used the `Check Updates` feature from UnRAID's Docker panel, and it successfully updated my container to use Java17.

So, what I think happened is that the AMP software itself updated internally, but because the Docker container was not manually updated, it didn't have Java17 and couldn't do everything it needed.

**Comment by judsonjames** [comment]
I'm closing this issue since it's resolved, but in case anyone else runs into an issue like this, they should probably use the `Check Updates` feature of UnRAID's Docker page and pull any updates. Even if the UI says it's updated, it may not actually be updated.

**Comment by MitchTalmadge** [comment]
Thanks for the details! It sounds like I need to find a way to disable AMP's own updates or otherwise make the update process more clear.

**Comment by judsonjames** [comment]
The easy solution would probably be adding a note in the README about updates to AMP. AFAIK, AMP doesn't have an event subscriber (at least from what I could find in [their wiki](https://github.com/CubeCoders/AMP/wiki/). Otherwise, CubeCoders might have something in their developer license on adding new panels that check for updates and notify the user to update?
