### ISSUE TITLE
Minecraft Bedrock Edition Support

### ISSUE THREAD

**Issue by MitchTalmadge** [MitchTalmadge/AMP-dockerized#11]
Getting a lot of errors when trying to start Minecraft Bedrock:

```
/home/amp/.ampdata/instances/Minecraft01/./Minecraft/bedrock_server: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/amp/.ampdata/instances/Minecraft01/./Minecraft/bedrock_server)
/home/amp/.ampdata/instances/Minecraft01/./Minecraft/bedrock_server: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /home/amp/.ampdata/instances/Minecraft01/./Minecraft/bedrock_server)
/home/amp/.ampdata/instances/Minecraft01/./Minecraft/bedrock_server: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by ./libCrypto.so)
```

Might have to switch to an Ubuntu image from Debian, trying that now.

**Comment by MitchTalmadge** [comment]
Having to install AMP manually since the Ubuntu image doesn't include `systemctl`

**Comment by MitchTalmadge** [comment]
Some success! 
![image](https://user-images.githubusercontent.com/8848080/71516971-2a9f9500-2869-11ea-9937-1fa443757f81.png)

**Comment by MitchTalmadge** [comment]
Having port issues but I think it's my own VPS.

**Comment by skylaar727** [comment]
Following our discussion in the Source thread, I've just checked out Bedrock. Was indeed the same issue here.

Interestingly enough the console inside AMP appears as if it lists 2 ports, similar to your screenshot above.

After investigating, it is the one that is set by ADS that is actually being used, not sure why the other port is there but that seems much more like an AMP issue not something to do with this docker.

As far as I can tell though, Bedrock is fully working. Just remember to open whatever ports you assign to minecraft in ADS as both TCP and UDP, or on a case by case basis per server.

If I get some more time i'll check out some of the other source games. But considering multiple source games as well as bedrock were just a result of UDP issues, I feel pretty confident they should all be working just fine too.

The starbound server I am running for a few friends has apparently had no issues either.

**Comment by MitchTalmadge** [comment]
This is such great news! Thank you for testing! I keep meaning to try it myself but I'm so overloaded with classwork that I can't find the time. :( The important thing is that it's working for you, which means it's likely going to work for others. I should definitely add a UDP information section to the README.

**Comment by MitchTalmadge** [comment]
Confirmed working after adding the udp flag to my config. Thank you for your hard work @skylaar727!! I'll update the README eventually.

**Comment by FractalHQ** [comment]
Hey @MitchTalmadge how did you add udp flag to your config?  Can't find documentation on this.

**Comment by MitchTalmadge** [comment]
> Hey @MitchTalmadge how did you add udp flag to your config?  Can't find documentation on this.  (I'm having this issue with official bedrock server on Debian, not using docker)

Hey! On Docker all I had to do was add `/udp` to the port forward listing, like `25565:25565/udp`. I did not have to do anything special with AMP -- Minecraft Bedrock is hardcoded to use a UDP socket.

If you describe your problem in more detail maybe I can help you figure out the issue.

**Comment by FractalHQ** [comment]
Ah ok- thanks!  I think I'm going to rebuild my server image using Ubuntu and try again- a lot of threads saying the problem is unique to Debian.  I'll let you know if I have issues- thanks so much for the prompt response!!
