### ISSUE TITLE
Java selection not working

### ISSUE THREAD

**Issue by KoalaBear0** [MitchTalmadge/AMP-dockerized#112]
So I'm trying to run an older version of MC which isn't being supported with JDK17. I change the java version for the instance (and even tried a fresh instance), but no matter what version I chose or which instance none of them change sdk. The logs indicate it found J11 and is using it, but I get thrown an error for not using an older version with the modloader.
[AMPLOG 2022-01-29 11-52-20.log](https://github.com/MitchTalmadge/AMP-dockerized/files/7965064/AMPLOG.2022-01-29.11-52-20.log)
is my log for this specific instance.

**Comment by MitchTalmadge** [comment]
Hi! The logs look like it is using Java 11 to start some kind of "ServerStarter", which uses the Java default. For this container, that is Java 17. However, I found that there's a config file you can change, which you can see an example of here:
 https://github.com/BloodyMods/ServerStarter/blob/master/server-setup-config.yaml

The option you want to change is `forcedJavaPath` and it should be set to `/usr/lib/jvm/java-11-openjdk-amd64/bin/java`

ServerStarter has a Discord server you could reach out to for help changing this option: https://discord.gg/A3c5YfV

Let me know if you figure it out!

**Comment by KoalaBear0** [comment]
> Hi! The logs look like it is using Java 11 to start some kind of "ServerStarter", which uses the Java default. For this container, that is Java 17. However, I found that there's a config file you can change, which you can see an example of here: https://github.com/BloodyMods/ServerStarter/blob/master/server-setup-config.yaml
> 
> The option you want to change is `forcedJavaPath` and it should be set to `/usr/lib/jvm/java-11-openjdk-amd64/bin/java`
> 
> ServerStarter has a Discord server you could reach out to for help changing this option: https://discord.gg/A3c5YfV
> 
> Let me know if you figure it out!

Thank you so much, I've been struggling with this for the last few days! Thank you so so very much you went above and beyond!
