### ISSUE TITLE
Trying to host Arma 3 server, but it updates infinitely. When I try to spool it up it just keeps giving me an error saying "could not enable 

### ISSUE THREAD

**Issue by Sporical** [MitchTalmadge/AMP-dockerized#117]
When I try to spool it up it just keeps giving me an error saying "could not enable linux core dumps. error 1"

**Comment by Padi1111** [comment]
Got the same problem here.

**Comment by IceOfWraith** [comment]
This should work fine in the latest debian-12 image that will be released soon. (I've tested all these I'm responding to, btw!) :)

**Comment by MitchTalmadge** [comment]
Re-open or make another issue if it still doesn't work.
