### ISSUE TITLE
Java 17 not showing up

### ISSUE THREAD

**Issue by Liquidtouch** [MitchTalmadge/AMP-dockerized#118]
I am trying to create a new instance with Minecraft 1.18.2 and my only option is Java 16. I have rebuilt the docker container but inside amp its still only showing java 16. Not sure how to get it up to 17?

**Comment by MitchTalmadge** [comment]
Are you sure you're on the latest version of the container? Please try pulling the latest and then try it. If you're unsure if you're on the latest, you can check the version of AMP itself on the Web UI. It should be 2.3.2.4

Let me know!
