### ISSUE TITLE
Trying to setup a TF2 server

### ISSUE THREAD

**Issue by Frazzer951** [MitchTalmadge/AMP-dockerized#119]
Will update fine and give `Success! App '232250' fully installed.`

But won't ever start.
After clicking start nothing appears in the console and I see an area that says `Application State: Starting` but it will sit like that forever and never actually start. If I look at the log for the instance it just has this message repeating 
`[15:20:51] [srcds:frazzer Warning] : The application stopped unexpectedly. Exit code 1`
I keep posting this message about every 4 seconds until I click abort. 
What can I do?

**Comment by NoahMaceri** [comment]
Second this issue but with a GMod server. Seems to be an issues with SteamCMD within the container

**Comment by Frazzer951** [comment]
> Second this issue but with a GMod server. Seems to be an issues with SteamCMD within the container

Make sure you have the server IP set to something other than `0.0.0.0`
It was a problem with the actual AMP software for me, not the docker itself

**Comment by NoahMaceri** [comment]
Thanks @Frazzer951, that worked

**Comment by darth2499** [comment]
How do I set the server IP to something else? Do I do it in the AMP instance?

**Comment by Frazzer951** [comment]
> How do I set the server IP to something else? Do I do it in the AMP instance?

Yea it should be in the same section where you configure all the other server settings on the AMP Interface
