### ISSUE TITLE
Minecraft Server starting at 0.0.0.0:25565

### ISSUE THREAD

**Issue by ToastArgumentative** [MitchTalmadge/AMP-dockerized#120]
Every time I go to start a Instance of Minecraft, the server starts at 0.0.0.0, and can't get an IP to connect.

On Latest version of Unraid and AMP. Using Unraid Docker.

**Comment by rbretmounet** [comment]
What steps did you take to solve it because I'm having the same issue

**Comment by ToastArgumentative** [comment]
Well for me it was because Xfinity doesn’t allow static ips from the device, so I had to do dhcp on the device and add a port to the device to make it static, then it worked.Sent from my iPhoneOn Jul 7, 2022, at 12:10 AM, rbretmounet ***@***.***> wrote:﻿
What steps did you take to solve it because I'm having the same issue

**Comment by rbretmounet** [comment]
Ok ill give that a try thanks

**Comment by ToastArgumentative** [comment]
Yeah it’s just very difficult and anoyying customer support didn’t even helpSent from my iPhoneOn Jul 7, 2022, at 12:18 AM, rbretmounet ***@***.***> wrote:﻿
Ok ill give that a try thanks
