### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ToastArgumentative** [MitchTalmadge/AMP-dockerized#121]
When i join my minecraft server, it instantly crashes, and no one can join it. we fall through the void for a couple minutes and then get timed out.

**Comment by Joly0** [comment]
Do you have any logs or anything that might help solve this issue? Minecraft Version, your server specs or anything?

**Comment by ToastArgumentative** [comment]
I found my issue I just forgot to close it.

My unraid server was doing a parity check, so the chunks couldn't load fast enough and was causing the server to crash, as I was spawning go in unloaded chunks.

**Comment by Joly0** [comment]
Ok, then close this issue please
