### ISSUE TITLE
Unable to run V Rising

### ISSUE THREAD

**Issue by Dalarialus** [MitchTalmadge/AMP-dockerized#124]
Hello!

Today, AMP was updated with the ability to run a V Rising server - According to [CubeCoders](https://www.reddit.com/r/vrising/comments/uxgdni/weve_added_support_for_v_rising_to_amp_on_both/ib26i1a/), it requires the server to be running `architecture i386`, `wine32`, `wine64` and `xvfb`.

To try and add these dependencies, I added a `startup.sh` file;

```
echo "Downloading dependencies for V Rising..."
apt-get update && \
apt-get install -y --no-install-recommends \
wine32 \
wine64 \
xvfb
apt-get -y clean && \
apt-get -y autoremove --purge && \
rm -rf \
/tmp/* \
/var/lib/apt/lists/* \
/var/tmp/*
```

Creating the instance and updating it run fine, but when I try to start the application, AMP produces the following warnings in console;

```
22:05:55: Success! App '1829350' fully installed.

22:06:12: /usr/bin/xvfb-run
          184: wine64: not found

22:06:12: Console
          /usr/bin/xvfb-run: 184: wine64: not found

22:06:12: /usr/bin/xvfb-run
          184: wine64: not found

22:06:12: Console
          /usr/bin/xvfb-run: 184: wine64: not found

22:06:12: /usr/bin/xvfb-run
          184: wine64: not found

22:06:12: Console
          /usr/bin/xvfb-run: 184: wine64: not found

22:06:12: /usr/bin/xvfb-run
          184: wine64: not found

22:06:12: Console
          /usr/bin/xvfb-run: 184: wine64: not found

22:06:12: /usr/bin/xvfb-run
          184: wine64: not found

22:06:12: Console
          /usr/bin/xvfb-run: 184: wine64: not found
```

Have I missed something obvious here? From the AMP console output, it looks like I'm missing dependencies, but the docker container logs indicate that they're installed.

**Comment by IceOfWraith** [comment]
This should work in the new `mitchtalmadge/amp-dockerized:staging-debian-12` that will be released soon.

**Comment by MitchTalmadge** [comment]
Please re-open if this happens in the latest release :)
