### ISSUE TITLE
Minecraft instance refuses to start

### ISSUE THREAD

**Issue by rlberry** [MitchTalmadge/AMP-dockerized#126]
After updating to 2.3.3.4 on both the ADS and Minecraft instances, the minecraft instance refuses to start. After selecting "Start Instance", the instance appears to start and then fails with no trace in the log file except that trying to login produces the following error: "[20:04:07] [ADS:Anonymous Error]  : Failure to make API call to Minecraft01 (http://127.0.0.1:8081/API/Core/GetAPISpec) - retried 10 times : Connection refused" Full log file from boot with sensitive info redacted is attached.

[ADS LOG.txt](https://github.com/MitchTalmadge/AMP-dockerized/files/8895504/ADS.LOG.txt)

**Comment by LostkingZ** [comment]
I think I have the same issue bud, any idea what's causing this?

**Comment by rlberry** [comment]
I ended up backing up the contents of my Minecraft folder with the server and completely nuked the container from orbit. After re-installing, I moved the server folder back in and recreated my schedules. Its working, but server itself was lagging bad right after creation. I left it running all night (turned off sleep mode) and I am going to look at it after work today.

**Comment by LostkingZ** [comment]
yeah, to get mine online I had to make a new instance and then copy the files over. left the old instances on though to hopefully troubleshoot what the problem is so I know I will be able to reboot the server in the future without having to go through the whole copy and paste scenario again.
