### ISSUE TITLE
How to change the licence field?

### ISSUE THREAD

**Issue by Shindur** [MitchTalmadge/AMP-dockerized#128]
Hey there, first time using this docker container and I finally got it to run, but it stops at the licence bit, which is to be expected.
However, where do I go to change the licence variable once I have bought my licence?

**Comment by harveydobson** [comment]
Hi @Shindur, 

My understanding is that LICENSE is an environment variable, https://github.com/MitchTalmadge/AMP-dockerized#environment-variables. 

So you should be able to include this in the environment directive of your `docker-compose.yml` or if you are using the docker run command, you can append `-env LICENSE=xyz` or `-e LICENSE=xyz` for the shorthand version.
