### ISSUE TITLE
Missing xvfb dependency for Core Keeper, causes instance to hang

### ISSUE THREAD

**Issue by judsonjames** [MitchTalmadge/AMP-dockerized#137]
This seems to be addressed already on the main CubeCoders AMP repo, linked [here](https://github.com/CubeCoders/AMP/issues/681)

This only needs to be updated in the Dockerfile by adding `xvfb` somewhere when installing [dependencies for AMP](https://github.com/MitchTalmadge/AMP-dockerized/blob/master/Dockerfile#L87).

Can `xvfb` be added to dependencies to allow CubeCoders to run? If not, I can try to fit time to write a PR.

**Comment by MitchTalmadge** [comment]
Hi! This dependency is only needed for this generic module right? In that case I'd suggest creating a startup script which installs the extra dependency. Check out the "Custom Scripts" portion of the Readme. Let me know if that makes sense and works for you!

**Comment by judsonjames** [comment]
Yeah, adding a custom script to the scripts volume solved the server init issue. 

FWIW to others who want to try making Core Keeper work, here's the `startup.sh` that I ended up going with

```shell
echo "Downloading dependencies for Core Keeper..."
apt-get update && apt-get install -y xvfb
```

AFAIK xvfb is the only dependency needed for Core Keeper to function as of 0.4.3-b0ed Early Access.

I'll close this issue since the startup script solved the listed issue. Thanks for pointing it out.
