### ISSUE TITLE
Minecraft 1.18.2 Failed to start and corrupted jar file.

### ISSUE THREAD

**Issue by zeepure** [MitchTalmadge/AMP-dockerized#138]
![unknown](https://user-images.githubusercontent.com/111927267/187976963-6bf9360f-50be-4bbd-b606-e54c4b560943.png)
![unknown (1)](https://user-images.githubusercontent.com/111927267/187976974-5564081a-6a73-4f9e-9529-8080a5c65d4c.png)
When starting Minecraft 1.18.2 instance, choosing Server Type: Forge, Forge Version: 40.1.73 and downloading/updating, it will successfully download all the required libraries and run.bat/sh. when trying to start said server it will say missing jar file (even though it is in the net\minecraftforge\forge\ folder) Copying the jar file to the root folder will resulted in valid or corrupted file. I'm running Unraid 6.10.3

**Comment by IceOfWraith** [comment]
I believe this can be closed. This seems around the time Forge changed from using a JAR file to a weird script approach. Mike has updated AMP to accommodate a while back.

**Comment by MitchTalmadge** [comment]
Thank you @IceOfWraith for the help!! It means a lot
