### ISSUE TITLE
TZ=Pacific/Auckland does not seem to work

### ISSUE THREAD

**Issue by itslukebtw** [MitchTalmadge/AMP-dockerized#146]
Hi, have just had a scheduled job go off that is set to run at 5:15am NZ time but has gone off at 6:15pm NZ.
I have TZ=Pacific/Auckland set in the Docker compose

**Comment by itslukebtw** [comment]
Just restarted AMP to get timings. Looks like the scheduled jobs still run in UTC instead of NZDT

Copying AMP Core...
Ensuring AMP user exists...
Ensuring correct file permissions...
Setting timezone from TZ env var...
Current default time zone: 'Pacific/Auckland'
Local time is now:      Wed Jan 11 08:43:45 NZDT 2023.
Universal Time is now:  Tue Jan 10 19:43:45 UTC 2023.

**Comment by IceOfWraith** [comment]
This is a limitation within AMP itself. Mike plans to add localized scheduled tasks eventually, but this was changed to UTC for all to avoid bugs in the meantime.

**Comment by MitchTalmadge** [comment]
Re-open if I'm wrong, but this looks to be available now: 

![image](https://github.com/user-attachments/assets/1591758a-56c3-4212-b994-64ad24c6222f)
