### ISSUE TITLE
Idea: Nested Docker Containers

### ISSUE THREAD

**Issue by ProjectSynchro** [MitchTalmadge/AMP-dockerized#147]
Would be nice to be able to use the native docker functionality in AMP, granted I have no idea how easy this would be to accomplish.

Is installing docker/moby enough to get this working? Will need to test and see.

**Comment by Joly0** [comment]
This has already been discussed here
https://github.com/MitchTalmadge/AMP-dockerized/issues/129
Docker in docker is not really something you should want. Better would be he approch to let amp access the hosts docker

**Comment by MitchTalmadge** [comment]
Duplicate of #100
