### ISSUE TITLE
Python and PIP

### ISSUE THREAD

**Issue by Toylerrr** [MitchTalmadge/AMP-dockerized#150]
Hello any chance to get Python and PIP added to the base docker image?

Trying to get Gatekeeper bot up and running under this and It depends on both of those packages.

https://github.com/k8thekat/GatekeeperV2

**Comment by MitchTalmadge** [comment]
I'll consider it! For now you can look at the Custom Scripts section in the readme and have it install on startup for you! :)

**Comment by IceOfWraith** [comment]
This will work in the latest dev if we add the `python3-venv` package to the list. That's a more recent addition to the AMP Docker images so it wasn't in my original changes. :)

**Comment by MitchTalmadge** [comment]
Let's do it!

**Comment by MitchTalmadge** [comment]
python3-venv has been added to the latest release! Please open an issue if it does not work. Thank you!
