### ISSUE TITLE
Where to setup webpanel the login and password?

### ISSUE THREAD

**Issue by JohnPBee** [MitchTalmadge/AMP-dockerized#151]
I installed everything and got it running, but have no idea how to login...
Was there a place to enter a login and password?

I didn't see anything in the docker-compose.yml file

**Comment by JohnPBee** [comment]
Nevermind, I found it;

USERNAME | The username of the admin user created on first boot. | admin
PASSWORD | The password of the admin user. This value is only used when creating the new user. If you use the default value, please change it after first sign-in. | password


That said, any idea where the physical location of the ../LocalBackups/ virtual folder is?

**Comment by IceOfWraith** [comment]
The folders are wherever you specify for the volume when creating the docker-compose.yml file. They would be inside each instances' folder.
