### ISSUE TITLE
Core Keeper server xvfb dependency issues

### ISSUE THREAD

**Issue by JimboDorian** [MitchTalmadge/AMP-dockerized#152]
An issue with amp in general is that Core keeper requires xvfb package to run otherwise will hang on "Starting application". 

I have used the startup script to install this dependency and I am still receiving the following error:
`/usr/bin/xvfb-run: 184 ./CoreKeeperServer: not found`

I will try do more debugging tonight but was hoping someone had already solved this.

**Comment by IceOfWraith** [comment]
This is fixed in the latest dev version to be released soon.

**Comment by MitchTalmadge** [comment]
Please try the latest release & re-open if there's a problem. TY!
