### ISSUE TITLE
 Server Sleep Mode Feature Issue IPV6 (Minecraft Paper Server 1.20)

### ISSUE THREAD

**Issue by noomis** [MitchTalmadge/AMP-dockerized#160]
Since the official AMP Support doesnt support this dockerized Version im putting my little Bug here, hopefully someone has a fix for this 

Hi guys i'm facing an annoying bug with Sleep Mode on my Minecraft Server because of using IPV6 only (only have a public ipv6 address) so as long as the Server/AMP doesnt get rebootet or anything everything works perfectly fine, but whenever i reboot my system or amp i get this annoying bug that IPV6 Server sleeping mode isnt working right from the start, so i always have to do the exact same following steps:

- shut down my  Paper Sever and switch the Server IP Adress Option to IPV4

- Start the Minecraft Server once and shut down after it booted

- switch the Server IP Adress back to IPV6

- start the Minecraft Server again

- force to sleep one time -> after that it works perfectly fine and automatic unless i reboot my system ._.

Does anyone have an Idea of what could be the Problem here to fix my little annoying bug?

Thanks for any help! :)

**Comment by IceOfWraith** [comment]
AMP doesn't support modded Minecraft and sleep mode. It's only guaranteed to work with vanilla Java Minecraft as it is. It sounds like this is an issue that can't be solved sadly.
