### ISSUE TITLE
AMP 2.4.5.x

### ISSUE THREAD

**Issue by MitchTalmadge** [MitchTalmadge/AMP-dockerized#164]
Looks like [the release process has changed](https://discourse.cubecoders.com/t/changes-to-the-release-process-going-forward/4032) with AMP 2.4.5.x and our GitHub Actions will need to be reconfigured. The endpoint we normally get versions from is stuck at 2.4.4.0: https://cubecoders.com/AMPVersions.json

```
{
    "InstanceManager": "2.4.4.0",
    "InstanceManagerCLI": "2.4.4.0",
	"AMPCoreMinimum": "2.3.0.0",
    "AMPCore": "2.4.4.0",
	"StreamVersions": {
		"Mainline": "2.4.4.0",
		"LTS": "2.4.0.6"
	},
    "ReleaseNotes": "https://discourse.cubecoders.com/t/amp-decadeus-2-4-4-release-notes/4129?utm_source=AMPUpdateNotice&utm_term=2440",
    "ModuleVersions": { }
}
```

**Comment by MitchTalmadge** [comment]
The install process has changed. Instead of downloading https://cubecoders.com/Downloads/AMP_Latest.zip we now need to download https://repo.cubecoders.com/ampinstmgr-latest.tgz as far as I can tell. Will have to investigate.

**Comment by PhonicUK** [comment]
`https://downloads.cubecoders.com/AMP/manifest.json` contains the new version information.

URL format for the archives is:

```
https://downloads.cubecoders.com/AMP/{stream}/{release.LatestBuild}/AMP_{release.Platform}.zip
```

**Comment by MitchTalmadge** [comment]
Thank you so much @PhonicUK !!

**Comment by MitchTalmadge** [comment]
https://github.com/MitchTalmadge/AMP-dockerized/pull/165

The update may be tested by pulling `mitchtalmadge/amp-dockerized:staging-decadeus`.

**Comment by MitchTalmadge** [comment]
FYI I have built an Unraid server at my house and am now testing it with the `staging-debian-12` image that @IceOfWraith graciously helped put together in #168 . So far so good

**Comment by MitchTalmadge** [comment]
https://github.com/MitchTalmadge/AMP-dockerized/releases/tag/v22
