### ISSUE TITLE
Succes: Terraria Server

### ISSUE THREAD

**Issue by excalbian** [MitchTalmadge/AMP-dockerized#169]
I just installed the unraid docker template, added my AMP license key, created a new terraria instance (which prompted me through the APM UI / web page to login to steam and steam guard) and while the download and initialization took a few minutes, everything just worked.

Unraid version: 6.12.3
Template: https://github.com/CorneliousJD/Docker-Templates/blob/master/amp.xml (installed through CA)
Template using docker from: https://hub.docker.com/r/mitchtalmadge/amp-dockerized/

Note that for other reasons, I choose to use the custom network (unique IP for the docker container) and didn't setup the MAC address.

The one thing to note is within the AMP UI for the Terraria server,  it shows the endpoint as using port `27015` although the port settings (and for the game to work) are for `7777`. This means the connection info (and direct steam link) don't work. I didn't have this issue before in my stand-alone APM installation, but it was also on an older AMP version, so I'm not sure 🤷.

**Comment by IceOfWraith** [comment]
This is a known issue with AMP. Nothing that can be solved here.

**Comment by MitchTalmadge** [comment]
Thanks for letting me know Terraria worked! I will add instructions for it when I get a chance.
