### ISSUE TITLE
Authentication token for admin requested by ManageInstance on behalf of 'admin' (user) - Project Zomboid

### ISSUE THREAD

**Issue by phigiaon** [MitchTalmadge/AMP-dockerized#174]
Running mitchtalmadge/amp-dockerized:staging-debian-12 on unraid trying to start a project zomboid server, fetched the latest from instance deployment and it said up to date but when starting the server 
Managed remote instance VaultHunter01 at http://192.168.69.148:8081/
Authentication token for admin requested by ManageInstance on behalf of admin
![pz](https://github.com/MitchTalmadge/AMP-dockerized/assets/96665459/fa766e42-7588-421d-8310-73004898f5ed)

**Comment by IceOfWraith** [comment]
Have you updated and started the server inside the instance? If so, go back to ADS (the main instance screen) and Right Click the instance to View Logs. Share the latest file here where you tried to run it and we can figure it out!
