### ISSUE TITLE
xvbf-run missing

### ISSUE THREAD

**Issue by c-def** [MitchTalmadge/AMP-dockerized#175]
Unable to launch a server for V Rising due to the following error: "Required system-level tool '/usr/bin/xvfb-run' does not exist - it may need to be installed manually by the user. Aborting startup."

**Comment by MitchTalmadge** [comment]
Hi! Can you try the image `mitchtalmadge/amp-dockerized:staging-debian-12` and see if it fixes the issue? :)

**Comment by MitchTalmadge** [comment]
Added to the latest release. Please re-open if there's an issue. Ty!!
