### ISSUE TITLE
Truenas scale

### ISSUE THREAD

**Issue by Tiny-Belt** [MitchTalmadge/AMP-dockerized#177]
Trying to deploy amp on truenas scale cobia, and I've been having the hardest time. I was finally able to access the webui. But now I'm running into it resetting repeatedly more than likely due to the storage configuration. I've tried a few different ways to get it to work but have been unsuccessful. If anyone has set this up as a custom app through truenas scale kubernetes please god help me 🙏. I will provide any details as fast as I'm able to. I just want to get this to work.

**Comment by Gaarindor** [comment]
TrueNAS has just released their Electric Eel version which now supports Docker Compose. Noting the age of this ticket and the recent changes with TrueNAS, I dare say this ticket can be closed and anyone with this issue should update to TrueNAS EE.

**Comment by MysteriousRSA** [comment]
I've had good luck with this yaml for a custom app:

`services:
  amp:
    container_name: amp
    environment:
      - LICENCE=[Your_Key]
    image: mitchtalmadge/amp-dockerized:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - [path/on/your/host]:/home/amp/.ampdata:rw`
User in TrueNAS Scale 24.10.0.2
