### ISSUE TITLE
Minecraft Bedorck 1.20.5 does not start anymore

### ISSUE THREAD

**Issue by BigMichi1** [MitchTalmadge/AMP-dockerized#184]
When starting the server a log entry is written and the server does not start

```
[06:54:11] /home/amp/.ampdata/instances/Main/./Minecraft/bedrock_server: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by MitchTalmadge** [comment]
Thanks for the report, I think this will be the solution:

https://stackoverflow.com/a/72633324

I'll find time to add a patch

**Comment by IceOfWraith** [comment]
This is a bug with AMP. The release Wednesday will fix it. My bad. :(

**Comment by MitchTalmadge** [comment]
Thanks @IceOfWraith !

**Comment by ForDefault** [comment]
Is the 2.4.7 update ‘Decadeus’ suppose to fix this issue? I tried updating in the  web UI but nothing changed in the version. Not sure if that is expected.
sidenote- I bought my license 3 years ago for minecraft bedrock - have yet to get it working for bedrock lol.

**Comment by IceOfWraith** [comment]
The release for 2.4.7 is coming soon and fixes this issue. The only way to get it right now is to switch it to the development build under `Configuration->New Instance Defaults` and make a new instance.

**Comment by IceOfWraith** [comment]
This was fixed in the latest AMP release. If you share your log we can maybe help. Right click the instance and View Logs if you can.

**Comment by Jacob-Lasky** [comment]
@IceOfWraith ah, I didn't realize AMP was updated!

I dug through my logs and found that the Forge jar wasn't being identified correctly. I redownloaded the correct version and everything is working again. Not sure what happened to cause this issue but glad it's fixed now!

**Comment by IceOfWraith** [comment]
The Forge folks messed around with how they handled the JAR files. It's been a moving target with them a few times.
