### ISSUE TITLE
 No login access

### ISSUE THREAD

**Issue by Mammutor** [MitchTalmadge/AMP-dockerized#188]
After I started my docker, I wanted to log in to my AMP and i got this screen:
![image](https://github.com/MitchTalmadge/AMP-dockerized/assets/44206081/c2775a01-cb49-4b90-91fc-c78489c4e189)
As you can see, there is no login. I restared my server. I redownloaded the image. And the log 
![image](https://github.com/MitchTalmadge/AMP-dockerized/assets/44206081/399d0d06-1eba-424b-b8df-f771c4a58952)
doesnt tell me that something is wrong.

**Comment by 3d6564** [comment]
Can you share how you launched the container? Are you using something like Portainer or a `docker run` command?
