### ISSUE TITLE
Incorrect CPU Usage?

### ISSUE THREAD

**Issue by MitchTalmadge** [MitchTalmadge/AMP-dockerized#19]
It seems that the CPU usage reported by AMP is much lower than the real CPU usage at all times. This might be a docker thing or it might be just my server. Can anyone confirm?

**Comment by MitchTalmadge** [comment]
@skylaar727 If you get bored sometime I'm interested to know if this happens for you too.

**Comment by skylaar727** [comment]
Ye i've been noticing the same, right now for example I have a minecraft modpack server running using 5.8GB of RAM with 3 players. AMP is reporting between 0 and 1% CPU usage, however netdata (this is also running in a docker container) is currently reporting around 4-6%, 10% or so if I'm deliberately stressing the server.

I would assume its possible for docker containers to read the real numbers else tools like netdata would be pointless to offer as docker containers. Not sure how easy it would be to add that compatibility into the image if AMP is looking to receive that info in its own way though.

As an aside I've been meaning to get round to trying out the preconfigured terraria generic module, if I do get to it i'll post an update on  the issue you opened regarding that too.

**Comment by MitchTalmadge** [comment]
Very weird. I'm gonna try running `top` inside my AMP docker container to see what it looks like from within. The developers of AMP say (having browsed through Discord history) that CPU usage is "directly from the OS," however I don't know how they are getting that info. If I can find out, might be able to narrow down why it's so inaccurate. The culprit is either docker or AMP, that's really the only two options I see here.

**Comment by MitchTalmadge** [comment]
top and uptime commands report correct statistics, so I'm convinced that AMP is obtaining its data in weird ways. If I get more time I'll dig into their binaries and see what I can find.

**Comment by MitchTalmadge** [comment]
This looks a lot better than it used to, I am not sure if it's perfectly accurate, but it does seem close.  will close this for now.
![image](https://user-images.githubusercontent.com/8848080/100399159-f0a5b880-300e-11eb-8394-3c55e03d7ced.png)
