### ISSUE TITLE
LAN Broadcast

### ISSUE THREAD

**Issue by nikaiwolf** [MitchTalmadge/AMP-dockerized#192]
I have had Amp since the original McMyAdmin original days. I have since upgraded to a 50 instance Amp license. I setup a Minecraft Java server. It works fine and runs. But my issue arises when I try to go join the server. I use my unraids machine IP address and the basic Minecraft port that is all on my LAN network. Minecraft on my PC doesn’t see it.

**Comment by nikaiwolf** [comment]
Figured it out. You need to add the ports for your instances in unraid docker for AMP

**Comment by nikaiwolf** [comment]
Also would like to note. Any restarting of the docker in unraid, say after a setting change or just trying to restart it, makes it fail to boot. Have to full stop and start to get AMP to load correctly.

**Comment by Joly0** [comment]
> Also would like to note. Any restarting of the docker in unraid, say after a setting change or just trying to restart it, makes it fail to boot. Have to full stop and start to get AMP to load correctly. 

You probably have something configured wrong then, cause.i dont have such issues
