### ISSUE TITLE
Can't login to the user interface

### ISSUE THREAD

**Issue by BomberPilot1** [MitchTalmadge/AMP-dockerized#194]
Can not login to user interface, reinstalled multiple times, user and password are default

**Comment by eroc1990** [comment]
Is this issue still ongoing? If so, are you able to pull logs from the container to show us what's going on?

**Comment by BomberPilot1** [comment]
I deleted multiple Times and it worked at some point.

Eric ***@***.***> schrieb am Fr., 19. Juli 2024, 18:12:
