### ISSUE TITLE
I might be stupid, but where is AMP pulling its backup capacity available data from?

### ISSUE THREAD

**Issue by eroc1990** [MitchTalmadge/AMP-dockerized#196]
I have a server that has a couple different instances configured. I just recently ran into an issue where a scheduled backup failed due to a lack of storage space, but it doesn't seem to be pulling that information from the expected location of my mapped Backups folder. Where exactly would I find this so I can change where it's looking to pull in an accurate remaining capacity number?

**Comment by IceOfWraith** [comment]
In the top right of AMP search for "Backup" and you should find two results. One for individual and one for total space limits.

**Comment by eroc1990** [comment]
Yup. That was me being stupid. Totally forgot about the instance global limit. Thanks!
