### ISSUE TITLE
Docker image size

### ISSUE THREAD

**Issue by heavygee** [MitchTalmadge/AMP-dockerized#204]
I have around 30 containers in my docker instance, this is the meatiest boy among them, clocking in at a chubby 4.66gb in use (and 1.6gb in dockerhub latest layer). Just wondering if there's a... lighter weight possibility for this?

**Comment by IceOfWraith** [comment]
Not really. This image has to include all dependencies for all game servers (Wine, Java, Python, etc...). If there's a Docker expert that knows a way to slim it then that'd be great but I think it's minimized pretty far already. Those tools take up a lot of space.
