### ISSUE TITLE
AMP cannot clone Spigot code if you only map the .ampdata volume

### ISSUE THREAD

**Issue by daj102** [MitchTalmadge/AMP-dockerized#23]
I found that when setting up a Minecraft Spigot instance, when I chose the Spigot server type, the notification would disappear very quickly with no status shown.  Looking in the Console, I found that there was a Permission Denied error on /home/amp/.gitconfig; this would be inside the container if (as I did) followed the instructions and only mapped the /home/amp/.ampdata volume.

To fix it, I mapped /home/amp to to a persistent volume - this created a .ampdata folder as well as a .config folder - but more importantly, ensured that the /home/amp folder had the right permissions for the user running AMP to be able to create the /home/amp/.gitconfig folder and clone the Spigot tools down into it.

**Comment by MitchTalmadge** [comment]
Oh interesting, I had always kind of wondered why it wouldn't download Minecraft reliably. Sounds like you might have found the issue! Thanks for the report, I will try to reproduce this and then we can come up with some ideas of how to correct it. :)

**Comment by MitchTalmadge** [comment]
Ok, you were totally right, the home directory of AMP did not belong to the Docker user. I have fixed this in #24 and must test it now to make sure it won't break any existing AMP installs. Feel free to test it too! The image to use is: 

`mitchtalmadge/amp-dockerized:staging`

**Comment by MitchTalmadge** [comment]
I've tested this on my own test instance and it upgraded as expected and is able to download/build Spigot.

**Comment by MitchTalmadge** [comment]
This should now be fixed in version 1.1.0: `mitchtalmadge/amp-dockerized:release-1.1.0`

Thanks! Open again if you still have problems.

**Comment by daj102** [comment]
Glad I could help :)  Thank you for fixing it; will give this a go soon.
