### ISSUE TITLE
AMP cannot update the terminal cursor position for displaying download progress

### ISSUE THREAD

**Issue by gitcob** [MitchTalmadge/AMP-dockerized#25]
I suddenly get this error when trying to start AMP:

```
[Info] Downloading AMP from https://cubecoders.com/Downloads/AMP_Latest.zip...
Unhandled Exception:
System.ArgumentOutOfRangeException: Value must be positive and below the buffer width.
Parameter name: left
  at System.TermInfoDriver.SetCursorPosition (System.Int32 left, System.Int32 top) [0x00021] in <11e8c3ad554843aabf495f404ae51ab6>:0 
  at System.TermInfoDriver.set_CursorLeft (System.Int32 value) [0x00016] in <11e8c3ad554843aabf495f404ae51ab6>:0 
  at System.ConsoleDriver.set_CursorLeft (System.Int32 value) [0x00000] in <11e8c3ad554843aabf495f404ae51ab6>:0 
  at System.Console.set_CursorLeft (System.Int32 value) [0x00000] in <11e8c3ad554843aabf495f404ae51ab6>:0 
  at InstanceManagerPlugin.LocalInstanceManager+<>c__DisplayClass172_1.<DownloadAndUnpack>g__ShowDownloadProgress|2 (System.Object sender, System.EventArgs e) [0x00000] in <6f2ae92962aa4edd9b4748666d12161e>:0 
  at ModuleShared.RunningTask.set_ProgressPercent (System.Int32 value) [0x0001a] in <c64a05644725485cb681794768148712>:0 
  at ModuleShared.Utilities+<>c__DisplayClass15_0.<DownloadFileWithProgressAsync>g__DownloadProgressChanged|0 (System.Object sender, System.Net.DownloadProgressChangedEventArgs e) [0x00091] in <c64a05644725485cb681794768148712>:0
```

My guess is that AMP started displaying some fancy ASCII-art download progress bar when downloading AMP_Latest.zip but did not anticipate being executed in a context where the terminal may not have valid dimensions. So it then tries to position the cursor based on some value that is calculated using the terminal dimensions, but since those are 0 or -1 or something, the position is out of range and the program crashes with an exception.

I'm not a linux expert, but maybe launching AMP in some sort of emulated terminal would help?

**Comment by MitchTalmadge** [comment]
Thanks for the report! Let me try to reproduce this and I'll get back to you.

**Comment by MitchTalmadge** [comment]
I haven't been able to reproduce this on either ampinstmgr v1.9.9.8 or v2.0.4 (latest). Does this happen every time you start the container? What operating system do you use? Thanks :)

**Comment by leechboy** [comment]
I am having the same issue. Running Docker on a Synology NAS DSM 6.2.3-25426 Update 2 which is Debian based. This happens every time I start the container.

I was able to run the entrypoint.sh line by line and I think that gitcob was correct. I did see a cute little progress bar

I am thinking if you add the --silent to the ampinstmgr CreateInstance that might fix the issue.

**Comment by MitchTalmadge** [comment]
Thanks for confirming the bug! I will do my best to solve this tonight. I was unaware of the `--silent` flag, looks like it was introduced after I made this image. Cool! I bet that will solve it. Thanks again!

**Comment by MitchTalmadge** [comment]
Unfortunately it does look like `--silent` prevents error messages from being printed. I'm trying to find a good solution to this

**Comment by gitcob** [comment]
Technically it's a bug in AMP - it should not crash just because there isn't enough space to draw the progress bar. I wouldn't count on them fixing it quickly though since it's not a supported use case.

**Comment by MitchTalmadge** [comment]
Okay, I have successfully reproduced this issue! My findings are that everything works unless you both (1) use the `-t` flag and (2) use the `-d` flag. 

In other words, starting a detached instance of this image while also allocating a pseudo-tty is what causes this crash. I think it is because docker can't figure out how to resize a detached terminal, or something along those lines.

Are you using both `-t` and `-d`, @gitcob  and @leechboy ? Could you try removing the `-t` flag? Let me know if it's needed for some reason, I don't normally use the `docker` command; I prefer `docker-compose`.

**Comment by leechboy** [comment]
For mine, I am actually using the built in Synology application. I will see
if there are some settings when deploying a Docker image.

**Comment by MitchTalmadge** [comment]
Oh that's good to know. I am coming up with ideas for how to solve this without messing with the Docker settings, but it's good to investigate what settings of Docker do and don't break things.

**Comment by gitcob** [comment]
I removed the `-t` flag and it works now! Good find!

In unraid, I think the `-d` flag is probably added by default.

**Comment by leechboy** [comment]
I know I could work around it when I open up a container terminal in
Synology and run the commands manually in the entrypoint.sh script.

Why do people need a progress bar in a terminal? LOL

**Comment by MitchTalmadge** [comment]
> 
> 
> Technically it's a bug in AMP - it should not crash just because there isn't enough space to draw the progress bar. I wouldn't count on them fixing it quickly though since it's not a supported use case.

Yeah, you are right. This is definitely an AMP bug. But I agree, they will not fix it. They have been very unsupportive of my idea to dockerize AMP, almost like I am insulting them somehow. Oh well.

**Comment by gitcob** [comment]
Yeah, I remember reading something like that. Something about not having control over which ports are being forwarded. But thanks for making a docker image anyway! The only other option for me and @leechboy would have been to run AMP in a VM, with all the downsides that come with that, for no good reason.

**Comment by leechboy** [comment]
I was actually trying to collapse my AMP VM into the Docker container
because I use Synology's HA component. I did get it to work manually and
got Minecraft and Factorio moved in but an ARK server choked. I'm going to
have to stay with the VM for at least the near future.

@MitchTalmadge, thanks for the work and for what it's worth, it did work
well, just the resources AMP uses on Synology for an ARK server was a bit
much as well as it was affecting my Plex Media Server (which is much more
important, lol).

Thanks again!

**Comment by MitchTalmadge** [comment]
I have solved this by passing the AMP output through grep which swallows the calls to resize the terminal and also hides the progress bar entirely. Things should work better now. I have more improvements coming in the next day or two as well.
