### ISSUE TITLE
Not really an Issue

### ISSUE THREAD

**Issue by Joly0** [MitchTalmadge/AMP-dockerized#31]
Hey, just wanted to say, that you should maybe add a full cleanup of apt after every apt install as this is considered good docker "coding" style. And maybe you should consider not installing sudo at all, its overall not best to install it, there are better, docker-friendly, alternatives to sudo, and so far i cant see anything that really needs sudo in your files.

**Comment by MitchTalmadge** [comment]
Hey! Thanks for the tips! I just found [this best practices page](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/) after researching some more and I will incorporate the ideas to help make this image better. And you appear to be right, I think I once used `sudo` but found a better solution, and forgot to remove it. 

Thanks!

**Comment by Joly0** [comment]
Hey, nice that my tips help you. I have created my own amp docker-container a while ago, its here on github aswell. But its overall a bit simpler than yours, but it applies most if not all of the best practices, like cleaning up apt or minimal layer-count and such things, but i have no time to work on own container anymore. Maybe i can fork yours and apply some of the practices so its less overall work for you aswell, for a better docker container together
