### ISSUE TITLE
Instances no longer auto updating

### ISSUE THREAD

**Issue by TABLE272** [MitchTalmadge/AMP-dockerized#33]
I have the container restart daily for backup purposes which until recently has always kept my AMP up to date. However lately, having first noticed it for 2.0.6.4 and now also 2.0.6.6, the instances aren't upgrading on their own. Looking in the docker log, AmpInstMgr itself is updating but the instance update does not appear to be triggering. This is the case both for the "Main" ADS instance and all game instances.

I've attached container start log below, wondering if anyone else has encountered this same issue or if I'm somehow broken it. I don't see anything obvious in the log aside from the Creating "Main" for ADS which fails as it already exists.

Simplying docker exec'ing into the container as the amp user and running `ampinstmgr upgradeall` upgrades successfully, as you would do if not running via docker. Just not sure why the behaviour has changed.

> Ensuring AMP User Exists...
> Checking for ampinstmgr updates...
> 2020-09-24 12:01:00 URL:https://cubecoders.com/AMPVersions.json [336/336] -> "/tmp/AMPVersions.json" [1]
> Latest Version: 2.0.6.6
> Current Version: 2.0.6.6
> No updates needed.
> Creating Main Instance... (This can take a while)
> [Info] AMP Instance Manager v2.0.6.6 built 18/09/2020 11:41
> [Info] Release spec: Release - built by CUBECODERS/buildbot on CCL-DEV
> [Info] Testing internet connection...
> [Info] Checking licence key...
> [Info] Licence Type:  AMP Network Standard
> [Info] Current Usage: 1
> [Info] Creating Instance: 'Main'
> [Info] Instance creation failed. You may not create multiple ADS instances within the same OS.
> Ensuring Main Instance will Start on Boot...
> Starting AMP...
> [Info] AMP Instance Manager v2.0.6.6 built 18/09/2020 11:41
> [Info] Release spec: Release - built by CUBECODERS/buildbot on CCL-DEV
> [Info] Waiting for AMP instance to start...
> [Notice] AMP instance Main is now running.
> [Info] Waiting for AMP instance to start...
> [Notice] AMP instance Minecraft08 is now running.
> [Info] Waiting for AMP instance to start...
> [Notice] AMP instance Minecraft07 is now running.
> [Info] Waiting for AMP instance to start...
> [Notice] AMP instance MattyEternal is now running.
> AMP Started.
> Entrypoint Sleeping. Logs can be viewed through AMP web UI or at ampdata/instances/Main/AMP_Logs

**Comment by MitchTalmadge** [comment]
Thanks for the report! Let me look into this and get back to you :)

**Comment by TABLE272** [comment]
Not a problem, been a long time since I've had to report anything over here. I'll let you know if I pick up any more leads too. 

I was having a look over the commit history to see if there were any obvious changes to the container that align with the timing, only thing that stands out is the change to user creation. Not sure if my originally starting to use this container means my old configuration is slightly incompatible. Gonna check that out first.

**Comment by MitchTalmadge** [comment]
Does the `.ampdata/instances/Main` directory exist? I probably shouldn't rely on directory names when checking if Main exists. I have a safer way of doing it but I'm curious if this is the problem. Maybe Main's directory got renamed somehow. Or maybe my image is accidentally looking for .ampdata outside of the home directory (I should have used an absolute path too).

**Comment by TABLE272** [comment]
Ye I think I'm one image out of date, haven't grabbed the newest image since the nightly build introduction so i'll give that a crack. It broke before that updated image was released just haven't had time to tinker with it. And ye my ADS instances is still located at `.ampdata/instances/Main`, definitely still exists. I'll pull the latest image and report back.

**Comment by TABLE272** [comment]
Yep, that shows me for not just updating first before creating an issue. Log now shows all the instances being checked for updates correctly as before.

I'll go sit in the corner XD Just didn't see any commits mentioning it so guess i dismissed it. Thanks for the help as always

**Comment by MitchTalmadge** [comment]
Oh interesting, does it still complain about making Main twice? I'm glad it's working! I am still going to improve the way Main is checked for existence since I am doing it unsafely, so I appreciate this issue!

**Comment by TABLE272** [comment]
Yep still mentions ADS cannot be created twice.

> 2020-09-24T21:09:08.093379228Z [Info] Checking licence key...,
> 2020-09-24T21:09:10.240647222Z [Info] This instance is already on the Mainline release stream.,
> 2020-09-24T21:09:08.314089963Z [Info] Creating Instance: 'Main',
> 2020-09-24T21:09:08.313811796Z [Info] Licence Type:  AMP Network Standard,
> 2020-09-24T21:09:08.313828711Z [Info] Current Usage: 1,
> 2020-09-24T21:09:08.317281113Z [Info] Instance creation failed. You may not create multiple ADS instances within the same OS.,
> 2020-09-24T21:09:08.337871223Z Setting all instances to use MainLine updates...,
> 2020-09-24T21:09:09.293766043Z > Main:,
> 2020-09-24T21:09:09.518930080Z [Info] AMP Instance Manager v2.0.6.6 built 18/09/2020 11:41,
> 2020-09-24T21:09:09.519084324Z [Info] Release spec: Release - built by CUBECODERS/buildbot on CCL-DEV

**Comment by MitchTalmadge** [comment]
Ok good to know! I will let you know once I have a fix out.

**Comment by TABLE272** [comment]
No worries, really appreciate the work. The fact I haven't even had to come back here to raise an issue for months is a testament to the work you put in, but always good to see more improvements :)

**Comment by MitchTalmadge** [comment]
I appreciate that! :) Here is the fix. Let me know if it solves "Main" being re-created on each start up. No rush!

https://github.com/MitchTalmadge/AMP-dockerized/releases/tag/5
(allow 30 min after this comment for builds to finish)

**Comment by TABLE272** [comment]
Yep looks to have solved it. New log extract below. 

> Ensuring AMP User Exists...
> Adding group 'amp' (GID 1001) ...
> Done.
> Adding system user 'amp' (UID 1000) ...
> Adding new user 'amp' (UID 1000) with group 'amp' ...
> Not creating home directory '/home/amp'.
> Checking for ampinstmgr updates...
> 2020-09-26 13:31:00 URL:https://cubecoders.com/AMPVersions.json [336/336] -> "/tmp/AMPVersions.json" [1]
> Latest Version: 2.0.6.6
> Current Version: 2.0.6.6
> No updates needed.
> Setting all instances to use MainLine updates...
> Main:
> [Info] AMP Instance Manager v2.0.6.6 built 18/09/2020 11:41
> [Info] Release spec: Release - built by CUBECODERS/buildbot on CCL-DEV
> [Info] This instance is already on the Mainline release stream.

**Comment by MitchTalmadge** [comment]
Very nice!
