### ISSUE TITLE
unRAID Support

### ISSUE THREAD

**Issue by CorneliousJD** [MitchTalmadge/AMP-dockerized#37]
Not an issue, but wanted to say THANK YOU for your work on this first and foremost.

I took the liberty of getting a template for this container setup for unRAID users!

If you want to create a note about it being available on unRAID under Community Applications you can.

unRAID specific support: https://forums.unraid.net/topic/98290-support-amp-application-management-panel-corneliousjd-repo/

Thanks again for doing this - made getitng a template for unRAID setup to use AMP pretty trivial :)

**Comment by MitchTalmadge** [comment]
Wow awesome! This is super good to see. Thanks for building on top of this image! I will definitely add something when I get some time.

**Comment by MitchTalmadge** [comment]
I added a blurb at the bottom of the README. Thanks for the help!
