### ISSUE TITLE
include xz-utils

### ISSUE THREAD

**Issue by kraetos** [MitchTalmadge/AMP-dockerized#38]
Be great if this container included xz-utils. Need it so the Factorio server can extract. The package is small, less than 1 MB.

**Comment by MitchTalmadge** [comment]
Yeah definitely! I'll play around with this when I get a minute.

**Comment by MitchTalmadge** [comment]
Ok, these are added and I had success getting Factorio downloaded and extracted via the Update button in AMP. Let me know if you run into any issues running Factorio! Also please let me know if your server works fully and I will add it to the supported list. Thanks @kraetos !
