### ISSUE TITLE
Ubuntu 20.04 Support

### ISSUE THREAD

**Issue by MitchTalmadge** [MitchTalmadge/AMP-dockerized#41]
We should look into updating to Ubuntu 20.04. Work has already started on this in the [staging-20.04](https://github.com/MitchTalmadge/AMP-dockerized/tree/staging-20.04) branch. 

I have currently updated the base Ubuntu image tag to 20.04, updated Java to version 11, and updated the srcds (TF2, GMod) dependencies based on those found in the `getamp.sh` script from the official CubeCoders AMP install page: https://cubecoders.com/AMPInstall (http://getamp.sh/)

Specifically, line 69 of `getamp.sh` lists these dependencies relating to srcds:

```
LIB32_PACKAGES="lib32gcc1 lib32stdc++6 lib32z1 libncurses5:i386 libbz2-1.0:i386 libtinfo5:i386 libcurl3-gnutls:i386 libsdl2-2.0-0:i386"
```

Unfortunately, `steamcmd`, which is used to download and launch srcds games and is created by Valve, seems to not work well in the 20.04 docker container. This error is received when checking for updates to TF2 and other srcds games:

```
Redirecting stderr to '/home/amp/Steam/logs/stderr.txt'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
/data/src/tier0/threadtools.cpp (4149) : Assertion Failed: Probably deadlock or failure waiting for thread to initialize.
[ 0%] Checking for available updates...
Thread failed to initialize
/data/src/tier0/threadtools.cpp (4149) : Assertion Failed: Probably deadlock or failure waiting for thread to initialize.
Thread failed to initialize
CWorkThreadPool::StartWorkThread: Thread creation failed.
Exiting on SPEW_ABORT
```

This is seen in other 20.04 images found in other projects on GitHub, e.g. https://github.com/steamcmd/docker/issues/30

It seems like there may be some incompatibility between steamcmd, Ubuntu 20.04, and Docker. I don't yet know what it is.

Help is appreciated to get this working. I have tested Minecraft and Factorio, they seem to work.

/cc @Joly0 I know you were interested in this.

**Comment by MitchTalmadge** [comment]
Just as a sanity check, I've confirmed that the dependencies we currently use for 18.04 allow `steamcmd` to work fine. Those same dependencies cannot be found on 20.04, which is why I updated the dependency list.

**Comment by Joly0** [comment]
Debian might be worth considering. I have built my own Amp container based on debian buster and as far as i can tell, steamcmd worked, and switching over to debian woulnt be that big of a problem

**Comment by Joly0** [comment]
And upgrading to java 11 might bring some problems with pre-1.13 modded minecraft.

**Comment by MitchTalmadge** [comment]
> Debian might be worth considering. I have built my own Amp container based on debian buster and as far as i can tell, steamcmd worked, and switching over to debian woulnt be that big of a problem

I tried this in the past and had some kind of problem which was solved by moving to Ubuntu, but I don't remember what it was. It's worth trying again!

> And upgrading to java 11 might bring some problems with pre-1.13 modded minecraft.

Good point! I guess we'll stick with Java 8. It appears to still be officially supported.

**Comment by Joly0** [comment]
I am gonna look into updating to 2004 or debian buster by the end of the week. Will prioritize Debian, but if thats not working, i try Ubuntu 2004 then and test the 2004-staging branch and look for incompatibilities and other problems.

**Comment by MitchTalmadge** [comment]
The steamcmd issues have seemingly gone away, must have been fixed in the last 6 months. I am looking forward to upgrading to Ubuntu 20.04.

**Comment by MitchTalmadge** [comment]
Ubuntu 20.04 has been running for multiple months now without any new issues. Closing this out.
