### ISSUE TITLE
Java Version 11

### ISSUE THREAD

**Issue by MitchTalmadge** [MitchTalmadge/AMP-dockerized#46]
Tonight the Paper MC team announced that they will be bumping the minimum Java version to 11 when Minecraft 1.17 is released in Summer of 2021. 

Info here: https://papermc.io/forums/t/java-11-mc-1-17-and-paper/5615

This means that if we do not update to v11, then many servers using our container will not be able to update to the latest Minecraft version. We currently use v8.

A problem is that some older versions of Minecraft do not work with Java 11. So we have two options:
1. Drop support for Java 8 in this container and potentially cause problems for people using it.
2. Find a way to support both versions.

Option 2 is ideal, and my only idea right now is to install both versions, with Java 11 being the default, and find some way for people who want to use Java 8 to somehow specify the binary to use.

There is a [modified JDK](https://github.com/ameisen/jdk-mc) as suggested earlier by @Joly0, but I don't feel comfortable forcing this unofficial build of Java on all the users of this container. I would prefer to find a solution using official builds.

Ideas are welcome!

**Comment by Joly0** [comment]
Supporting both versions would definitly be the best option, but its not quite possible, as the jar somehow needs to know which jvm he needs to use. The simplest option would be to use the unofficial jdk i suggested. The best official solution would be to use java 11 (or maybe 14/15 as there is not alot of change between those versions) and maybe add a "portable" installation of java somewhere in the docker container and instruct users to add a specified path to the appropriate minecraft.kvp file of the amp instance.

**Comment by Joly0** [comment]
Btw, this question got asked by myself and others in the official cubecoders discord server, but we shouldnt expect an answer before 07.12.20, as the developer of amp has taken a break for a few days

**Comment by MitchTalmadge** [comment]
![image](https://user-images.githubusercontent.com/8848080/101591294-72033080-39a9-11eb-83ee-174d10520d46.png)

Well this is good news! Next update will have a Java selector. This will make it easy to add Java 11. The biggest concern I have right now is how to upgrade without breaking Minecraft servers that are currently requiring Java 8.

**Comment by MitchTalmadge** [comment]
I haven't worked on this much but here is a branch for it: https://github.com/MitchTalmadge/AMP-dockerized/tree/staging-java

**Comment by Joly0** [comment]
Looks to me like the only option is to set java 8 as default and add java 11 additionally, that shouldnt break anything. Although thats not really future-proof. I would just make java 11 the default and make a big update disclaimer, that people have to adjust their settings. Someday we have to move on, and i would like to make that earlier then later

**Comment by MitchTalmadge** [comment]
> I would just make java 11 the default and make a big update disclaimer, that people have to adjust their settings. Someday we have to move on, and i would like to make that earlier then later

I agree and this is probably what we should do

**Comment by TABLE272** [comment]
So this update is now live as part of 2.0.8.8. I went ahead and installed java-11-openjdk-amd64 as a test and AMP is correctly recognising both Java 11 and Java 8 and the minecraft server log indicates its using Java 11 correctly when set to this.

In the discord server Mike has recommended adoptopenjdk-11-hotspot however. Regardless, it appears atleast from my "does it start" test that there shouldnt be much hassle other than including whichever version of java. Doesn't appear we'll need any further changes to make it work.

**Comment by MitchTalmadge** [comment]
Thanks for the great information! Looks like 2.0.8.8 was automatically built today by our GitHub Actions script, so now I can begin work on testing the installation of Java 11 and 8 together. :) I'll let you know once I have some results.

**Comment by MitchTalmadge** [comment]
Well good news, I installed both `openjdk-11-jre-headless` and `openjdk-8-jre-headless` and both versions show up and work! 

![image](https://user-images.githubusercontent.com/8848080/101973598-65274c80-3bf6-11eb-9ea1-68b2f616a6ea.png)

Some logs for proof that it works:

![image](https://user-images.githubusercontent.com/8848080/101973677-07473480-3bf7-11eb-9dce-46f3c2fccb81.png)

![image](https://user-images.githubusercontent.com/8848080/101973656-d7982c80-3bf6-11eb-99d1-206d50297e97.png)

Also the version 11 is selected as default which is desirable. There is a bit of weird thing in that Java 8 shows up twice, but I opened a terminal in the container and found that only one instance of Java 8 is installed:

![image](https://user-images.githubusercontent.com/8848080/101973608-86883880-3bf6-11eb-8fe9-8ac88670b4cd.png)

It might be an AMP bug. Both options produce the same results and work the same, so whatever.

**Comment by MitchTalmadge** [comment]
The duplicated Java 8 is an AMP bug due to not following symlinks. I'm not going to worry about it. I've been running the new build on my production Minecraft server for a bit and it's gone very well. I think we are safe to move this into a release.

**Comment by MitchTalmadge** [comment]
Deployed as version 9. Builds will roll out soon.
