### ISSUE TITLE
Minecraft Not broadcasting to LAN/ Unraid

### ISSUE THREAD

**Issue by torodiesel** [MitchTalmadge/AMP-dockerized#59]
I have noticed that everything I try to do on unraid to get the port 25565-25566 to broadcast to the local machines does not work. I have disabled firewalls and changed IP's but it still does not show. Is this not supported? I tried with a host and a Bonded interface.
![Capture](https://user-images.githubusercontent.com/52382226/107160429-20a0fe80-6964-11eb-8478-8eba4081c94d.PNG)

**Comment by Joly0** [comment]
> I have noticed that everything I try to do on unraid to get the port 25565-25566 to broadcast to the local machines does not work. I have disabled firewalls and changed IP's but it still does not show. Is this not supported? I tried with a host and a Bonded interface.
> ![Capture](https://user-images.githubusercontent.com/52382226/107160429-20a0fe80-6964-11eb-8478-8eba4081c94d.PNG)

I dont know if this is still a problem for you, but i can definitly tell that amp on unraid is working perfectly regarding the network
![image](https://user-images.githubusercontent.com/13993216/120833555-3618e480-c562-11eb-8ea3-5a1fd0a07c31.png)

There might be something wrong with your network setup, or your docker setup entirely

**Comment by byeuji** [comment]
I'm having this issue with the instances I've set up inside Amp-Dockerized (Minecraft and Valheim on default ports 25565-25575 and 5678-5688). 
I opened the ports on the firewall using UFW initially, then disabled the firewall entirely. Then I installed GUFW and reset the rules, then I reviewed iptables, then I reviewed `lsof -i -P -n` and `netstat -tulpn`

![image](https://user-images.githubusercontent.com/16928099/124400523-06333d00-dcd8-11eb-9712-609fd9ec5319.png)

In all cases, the instances inside Amp are invisible on the local network (including with the firewall off entirely). When I run an nmap scan of 25565, I get "25565/tcp closed minecraft". 

I have 3 other containers (Plex, Portainer and Deluge) all working normally and visible outside my local network. Like Amp, I have integrated SSL with each of these services, and they're all certifying correctly (including Amp-Dockerized's WebUI). It's *only* the instances that aren't showing up.

Here are the ports in my Portainer container management for Amp-Dockerized: 
![image](https://user-images.githubusercontent.com/16928099/124400396-e51e1c80-dcd6-11eb-94f1-f6658ae039de.png)

![image](https://user-images.githubusercontent.com/16928099/124400504-c9ffdc80-dcd7-11eb-8736-53fc61f8d32a.png)

The "Network" was set to "amp-dockerized_default" initially -- I've tested these scenarios on "bridge" as well. 

I'm not sure if there's some network configuration I can do from within the instance to make it visible?
![image](https://user-images.githubusercontent.com/16928099/124400611-95405500-dcd8-11eb-9aa3-91ea1d1027e6.png)

I'm not an expert with iptables, so I'm hoping there's something glaringly obvious with these screenshots.

**Comment by xannor** [comment]
I could be wrong about current/future versions, but I believe the broadcast to lan is only a feature of the client, (and I think MineOS emulated) so unless AMP provides this ability, you will not get a broadcast from a stand-alone server. 

(I found an old discussion talking about it https://discourse.codeemo.com/t/automatically-showing-server-in-lan/114/5 and in there is a link to a python script.) 
So unless AMP implements this in their plugin it would not work, either by providing the broadcast as part of the manager (similar to MineOS), or running something with the instance.

**Comment by MitchTalmadge** [comment]
Unfortunately I don't think we can do this. But if someone can prove me wrong or provide some info on how to do it, please do & let me know!
