### ISSUE TITLE
Java 16

### ISSUE THREAD

**Issue by multicm** [MitchTalmadge/AMP-dockerized#64]
What is the easiest way for me to upgrade this docker to include java 16? I need it for Minecraft version 21w19a

**Comment by MitchTalmadge** [comment]
I will look into updating the container to Java 16 since it will become the minimum version for Minecraft. Thanks for bringing this up! I'll try to have something out quickly.

**Comment by kevinpthorne** [comment]
Possible conflict: https://github.com/MitchTalmadge/AMP-dockerized/issues/41#issuecomment-734691511

**Comment by OrionH** [comment]
I was able to add Java 16 to the container using these commands as a temporary solution. 

add-apt-repository ppa:linuxuprising/java
apt install oracle-java16-installer --install-recommends

**Comment by MitchTalmadge** [comment]
I've finished adding and testing Java 16 in staging. I will merge it tonight if I can get my new CI/CD to play nicely.

**Comment by MitchTalmadge** [comment]
Java 16 is now a part of the latest release (v16) of this container. You can access it in the Java section of the AMP settings. Default remains Java 11 at least until Java 17 is released in September since it is the next LTS.
