### ISSUE TITLE
No longer getting up to date info in console or PC Usage stats

### ISSUE THREAD

**Issue by radwiimp** [MitchTalmadge/AMP-dockerized#65]
I updated to the most recent version (v2.1.1.4, built 07/05/2021 19:00), running it on my Unraid server. But since updating I'm no longer getting updates on the CPU/MEM/Users tab, and I have to refresh every time to see what is happening in the console for my MC server, it no longer shows up in real-time. Is this a bug, or did I accidentally click a setting...?

[https://i.imgur.com/lQ7umU1.png](url)

**Comment by MitchTalmadge** [comment]
Thanks for the report, I will test this and see if I run into the same problem!

**Comment by radwiimp** [comment]
Looking a bit further, this might not be an actual bug. This could be related to changes they made in the instance metrics and config files, so it might be that I just need to edit those and maybe read the patch notes first lol. However, not sure if that would explain the issue of the console real-time updates not happening.

**Comment by MitchTalmadge** [comment]
Actually I am seeing the same problem. Looking for a fix now.

**Comment by MitchTalmadge** [comment]
I think CubeCoders had a bug and then released a patch with the same version number, so my auto-update script did not have a way to know about it. If you pull the latest image, it appears to be fixed for me. Clear browser cache if you don't see changes. Let me know!

**Comment by radwiimp** [comment]
The update also fixed it for me. Thanks and great work!

**Comment by MitchTalmadge** [comment]
Happy to help!
