### ISSUE TITLE
Warn if LICENCE not provided

### ISSUE THREAD

**Issue by MitchTalmadge** [MitchTalmadge/AMP-dockerized#7]
Right now LICENCE defaults to "notset" which just causes the activation to fail. Might be nice to provide a more user friendly warning ahead of time by checking if the variable is actually set.

**Comment by Joly0** [comment]
Maybe leave the licence varaible blank and add something like that to the main.sh 
`if [ -z ${LICENCE+x} ]; then echo "Error: A licence for AMP from cubecoders.com is required and must be specified in the LICENCE environment variable"; exit 1; fi`

**Comment by Joly0** [comment]
btw got that from here https://github.com/othrayte/docker-cc-amp/blob/master/start.sh if interested. Used it in my Docker container once, until i removed the whole part creating an instance in the script and started using ampinstmgr quickstart

**Comment by Joly0** [comment]
I think this is fixed?

**Comment by MitchTalmadge** [comment]
Yep! I will close it once I merge in the changes to master.
