### ISSUE TITLE
Instances loose/forget licence after update

### ISSUE THREAD

**Issue by Joly0** [MitchTalmadge/AMP-dockerized#74]
After an update, the instances "forget" the licence and therefore are unable to start.

This needs to be fixed manually by using the command "ampinstmgr --reactivateall $licence" after every new update.

I could make a PR to reactivate the instances in the startup script, though i am not sure if this problem is only occuring for me or if this might be a general issue

**Comment by Joly0** [comment]
![image](https://user-images.githubusercontent.com/13993216/120835076-27cbc800-c564-11eb-827e-0f4b71ad1de7.png)
![image](https://user-images.githubusercontent.com/13993216/120835180-43cf6980-c564-11eb-8e4a-9bb8abf9c44e.png)

Hm.. i knew i forgot something... everday one is learning something new... its even marked as Important.

Still there should be a function in the code for the dumbass idiots like me who dont read the full documentation and forget to set the extra parameter.

Afaik cubecoders dont deactivate licences if the limit gets exceeded and updates them every few days. So it shouldnt be a problem to implement a function to reactivate the instances after such a case

**Comment by MitchTalmadge** [comment]
Yeah it would be worth looking into a way to detect if the MAC is static. I will see if there's anything I can do!
