### ISSUE TITLE
Possible to add dependency to clear console warning in Valheim?

### ISSUE THREAD

**Issue by Dalarialus** [MitchTalmadge/AMP-dockerized#75]
Valhiem gives console errors due to the absence of the 32-bit SDL library.

The errors look like this;
```
Loading Steam API...Failed to init SDL priority manager: SDL not found
Failed to set thread priority: per-thread setup failed
Failed to set thread priority: per-thread setup failed
```
This should be fixable by installing `libsdl2-2.0-0:i386`.

I'm not sure if your image has Debian's multi-arch support enabled or not, but if it isn't, it my be necessary to `dpkg --add-architecture i386`.

[Reference](https://github.com/ValveSoftware/steam-for-linux/issues/7036)

**Comment by MitchTalmadge** [comment]
Sure! I will try to reproduce and fix this :)

**Comment by MitchTalmadge** [comment]
If you are still using this image, please try updating to `mitchtalmadge/amp-dockerized:staging-20.04` and let me know if the issue is fixed. Thank you!

**Comment by Dalarialus** [comment]
Hey there! I've just tried out `mitchtalmadge/amp-dockerized:staging-20.04` and I'm still getting SDL warnings in the AMP console;

```
Warning: failed to init SDL thread priority manager: SDL not found
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
```

I'll try and do a little more investigation around my night shifts. Does this image include both the 32bit and 64bit versions of the SDL library?

Many Thanks :)

**Comment by MitchTalmadge** [comment]
Hiya! I am using `libsdl2-2.0-0:i386`. Ubuntu 20.04 has been merged to master so if you go to the root of the repository and open the `Dockerfile`, you can look at the dependencies I have installed and let me know if you see any changes! I'll research this more too. Sorry it didn't solve the problem yet!

**Comment by Dalarialus** [comment]
So I've done a bit more research on my night shift :)

According to [This comment](https://github.com/ValveSoftware/steam-for-linux/issues/7036#issuecomment-803258219) it looks like other people are having success when both the `i686` **and** `amd64` versions of `libsdl2-2.0-0` are installed.

I've checked the package lists on the Ubuntu 20.04 box that I'm planning on migrating away from and can confirm that it has both versions installed, and that it isn't displaying the console warnings about thread priorities.

With a bit of luck, this should crack it, as well as solving this issue for any other games using `SteamCMD` on AMP :)

**Comment by MitchTalmadge** [comment]
@Dalarialus Fantastic! Please try `mitchtalmadge/amp-dockerized:staging-sdl`, I have added the 64 bit lib there :)

**Comment by Dalarialus** [comment]
This appears to be an improvement. The SDL thread priority manager error is gone, but now I'm seeing different errors. Something must still be missing - I'll continue investigating >.<

```
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
```

**Comment by Dalarialus** [comment]
On further investigation, this looks like a separate issue, so I'd definitely suggest merging `:staging-sdl` into `:latest` :)

According to the [manpage,](https://man7.org/linux/man-pages/man2/setpriority.2.html) `setpriority()` will fail on Linux if the caller didn't have the `CAP_SYS_NICE` capability.

Digging into that, I found [this](https://github.com/moby/moby/issues/30122) which mentioned `cpu.rt_runtime_us` and pointed to [this](https://github.com/moby/moby/pull/23430) for further explaination.

These references are getting a bit beyond my scope of knowledge though, and I'll need to do a little more learning before I can dig much further into it.

**Comment by MitchTalmadge** [comment]
Wow thanks for doing all that research! I will do some of my own and hopefully we can come to a fix. I will get that SDL library out to latest once I have some free time.

**Comment by Dalarialus** [comment]
No problem! I'm not sure how much use my research will be though! All I know is that installing the 32 and 64-bit versions of SDL cleared all of the errors when I was running it outside of docker. I'm wondering if there's another package from a recommended dependency or a docker permissions issue at play here somewhere >.<

**Comment by Dalarialus** [comment]
Slightly tangential request: Would it be possible to add `libc6` and `libc6-dev`? These appear to be dependencies for running the popular Valheim Plus mod :) [Reference](https://valheim.plus/installation#feature-3)

**Comment by Dalarialus** [comment]
I've been doing a bit more looking around and I'm wondering if I'm overthinking things a little. 

ich777's container over at the Unraid forums appears to be running without errors and the only real difference that I can see is that they're running `libc6-dev' in their build as well as both versions of the `sdl` library. Maybe worth a try on the staging branch? Again, this should allow Valheim Plus to run, which is a nice side benefit :D

[Reference](https://forums.unraid.net/topic/79530-support-ich777-gameserver-dockers/?do=findComment&comment=951136)

**Comment by Dalarialus** [comment]
Is there any chance of adding `libc6-dev` to the `:staging` branch for testing?

**Comment by MitchTalmadge** [comment]
I think that `libc6-dev` is already included in the image as part of another dependency. However, I have come up with a solution that will allow you to install any dependencies you can imagine, or even do other advanced things: custom startup script!

If you pull `:staging-scripts` then you can add the volume `./scripts:/home/amp/scripts/` and inside place the script `startup.sh`, containing something like the following:

```sh
echo "Downloading dependencies for Valheim Plus..."
apt-get update && \
apt-get install -y \
        libc6 \
        libc6-dev
```

When I did this, I got the following result:

![image](https://user-images.githubusercontent.com/8848080/131209788-473768a4-a9c4-4478-acd6-00e3176887bb.png)

It seems to think the dependencies already exist. Have you had trouble with your mod not working due to not having these?

**Comment by Dalarialus** [comment]
I've been poking around with my config and it looks like the problem is solved - I'm not entirely sure how, but after re-doing my docker template, using the `:staging-scripts` branch and making sure that `--cap-add=SYS_NICE` is in my starting options, the errors are cleared.

Thanks for all of your hard work in developing and maintaining this container!
