### ISSUE TITLE
Unable to load Minecraft, Permission Issues

### ISSUE THREAD

**Issue by zackbcom** [MitchTalmadge/AMP-dockerized#76]
Loading up a default config and starting up Minecraft 1.17 causes some permission issues. I'm unable to start minecraft or save any Minecraft Server settings in the UI. 
I think it's related to all moduals I'm unable to load Factorio as well.

UID and GUID are my local user.
This user is apart of the Docker group.
I'm running on Ubuntu 20 Host.
I've tried setting all the files/folder to 777

Adding `privileged: true` to the docker-compose config Seems to fix the issues, but probably isn't the right solution.

Config:
````
  amp:
    container_name: amp
    image: mitchtalmadge/amp-dockerized:latest
    restart: unless-stopped
    mac_address: 02:42:AC:3C:EB:F8 # Please see the README about this field.
    ports:
      - 25565:25565 # For Java Edition (TCP)
      - 8125:8123
      - 19132:19132/udp # For Bedrock Edition (UDP)
      - 25570:8080 # Maybe you already have something running on 8080, so we could map to 25570. Remove if you want to use 8080.
    volumes:
      -  $USERDIR/docker/amp/data:/home/amp/.ampdata
    environment:
      TZ: ${TZ}
      UID: ${PUID}
      GID: ${PGID}
      LICENCE: ""
      MODULE: Minecraft
````

Minecraft 1.17 Error:
````
java.lang.RuntimeException: java.nio.file.FileSystemException: .: Operation not permitted
at dib.<init>(SourceFile:98) ~[minecraft_server.jar:?]
at dib.a(SourceFile:105) ~[minecraft_server.jar:?]
at net.minecraft.server.Main.main(SourceFile:122) [minecraft_server.jar:?]
Caused by: java.nio.file.FileSystemException: .: Operation not permitted
at sun.nio.fs.UnixException.translateToIOException(UnixException.java:100) ~[?:?]
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
at sun.nio.fs.UnixPath.toRealPath(UnixPath.java:852) ~[?:?]
at dib.<init>(SourceFile:96) ~[minecraft_server.jar:?]
````

Factorio Error
````
Error Util.cpp:83: filesystem error: cannot make canonical path: Operation not permitted [/home/amp/.ampdata/instances/ATM601/factorio/bin/x64/../../data]
````

**Comment by MitchTalmadge** [comment]
I've been trying to reproduce this but I am unable to. I have never run into permission issues like this before, but this is the second report (see https://forums.unraid.net/topic/98290-support-amp-application-management-panel-corneliousjd-repo/?do=findComment&comment=1001689). 

Your `docker-compose.yml` file looks correct. Maybe try another volume and run the container as root? Just to debug and see if it can gain permissions.

Sorry that I am not much help right now.

**Comment by RedSparr0w** [comment]
Getting this same error with all new/existing Minecraft instances (running latest build with java 16)

**Comment by MitchTalmadge** [comment]
Thanks everyone. I am getting more reports of this and it looks like it is limited to Minecraft 1.17. I am trying to find a solution, sorry it has taken a while. Please let me know if anyone discovers anything.

**Comment by MitchTalmadge** [comment]
> Getting this same error with all new/existing Minecraft instances (running latest build with java 16)
> 
> > Adding `privileged: true` to the docker-compose config Seems to fix the issues, but probably isn't the right solution.
> 
> Exact same here too.

Are all these MC instances on 1.17?

**Comment by MitchTalmadge** [comment]
Is anyone _not_ using UnRaid?

**Comment by MitchTalmadge** [comment]
Seeing similar problems on other UnRAID containers. https://forums.unraid.net/topic/92533-support-binhex-mineos-node/?do=findComment&comment=1003851

**Comment by RedSparr0w** [comment]
I was seeing the error on all instances running the following versions:
`1.16.5`, `1.12.2`, `1.8.8`

**Comment by MitchTalmadge** [comment]
Good to know, thank you!

**Comment by RedSparr0w** [comment]
Was also happening to my BungeeCord instance IIRC, and the servers were on Paper and Spigot

**Comment by MitchTalmadge** [comment]
If you have free time, please try version `mitchtalmadge/amp-dockerized:staging-20.04` and let me know if it works again. Thank you!

**Comment by RedSparr0w** [comment]
Everything looks to be running perfectly on `mitchtalmadge/amp-dockerized:staging-20.04`

Thanks for the help 👍

**Comment by MitchTalmadge** [comment]
Cool! Closed for now, let me know if anyone runs into this again.
