### ISSUE TITLE
Can't download/compile spigot 

### ISSUE THREAD

**Issue by jfeeser** [MitchTalmadge/AMP-dockerized#77]
Hi there, i'm having some issues running the container on Unraid - the AMP container starts normally and i'm able to log in and start a minecraft instance.  However, once i set it to use spigot as the server, i get the following in the instance/spigotbuild/BuildTools.log.txt

```
1 packages, 0 classes, 0 fields, 0 methods
Remapping final jar
Remapping jar...  0%
Remapping jar... 10%
Remapping jar... 20%
Remapping jar... 30%
Remapping jar... 40%
Remapping jar... 50%
Remapping jar... 60%
Remapping jar... 70%
Remapping jar... 80%
Remapping jar... 90%
Remapping jar... 100%
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE
Exception in thread "main" java.lang.RuntimeException: Error running command, return status !=0: [sh, /home/amp/.ampdata/instances/FeezoniaMinecraft/Minecraft/spigotbuild/apache-maven-3.6.0/bin/mvn, -Dbt.name=3096, install:install-file, -Dfile=work/mapped.d7866d9c.jar, -Dpackaging=jar, -DgroupId=org.spigotmc, -DartifactId=minecraft-server, -Dversion=1.16.5-SNAPSHOT]
        at org.spigotmc.builder.Builder.runProcess0(Builder.java:899)
        at org.spigotmc.builder.Builder.runProcess(Builder.java:841)
        at org.spigotmc.builder.Builder.runMaven(Builder.java:819)
        at org.spigotmc.builder.Builder.main(Builder.java:494)
        at org.spigotmc.builder.Bootstrap.main(Bootstrap.java:27)
```

How do i fix the java configuration?

**Comment by MitchTalmadge** [comment]
I am trying to reproduce this but having no luck. Mine succeeds when I click "Download/Update":

![image](https://user-images.githubusercontent.com/8848080/121787695-d5526300-cb84-11eb-9869-e6083c293995.png)

Using these settings:

![image](https://user-images.githubusercontent.com/8848080/121787700-e00cf800-cb84-11eb-87f0-e7673a0724e2.png)

Tried on both Java 11 and Java 16.

I don't use Unraid but I don't think it should change the behavior since this is a Docker image. Do you have any other configuration changes?

**Comment by jfeeser** [comment]
Nope, everything else is default.  Weirdly when i run the container privileged it works just fine, so at least i've got a workaround.

**Comment by MitchTalmadge** [comment]
Oh that's good to know. Maybe I have a permissions issue somewhere.

**Comment by ScreepCode** [comment]
I use the Docker also in Unraid and have the Same Problem.
After the Update to "Ganymede" for 24.6, my Server does not Run.
I even reinstalled the whole docker, which isn´t fixing the error.

**Comment by MitchTalmadge** [comment]
Can you try `mitchtalmadge/amp-dockerized:staging-20.04` and let me know if the issue goes away? Thank you!

**Comment by ScreepCode** [comment]
Hey Mitch, 
this update fixed the error.
Now the Server is running.
Can you explain, what the error was?

**Comment by MitchTalmadge** [comment]
@ScreepCode The way I had to install Java 16 in Ubuntu 18.04 was a bit hacky, and with the update to 20.04, the installation method is more robust. Feel free to keep using staging-20.04 and I will ping you when I release it formally.

**Comment by MitchTalmadge** [comment]
Let me know if anyone still runs into this problem.
