### ISSUE TITLE
Multiple Minecraft Servers?

### ISSUE THREAD

**Issue by judsonjames** [MitchTalmadge/AMP-dockerized#84]
Diagnostic Info
```
OS | Linux
Platform | Ubuntu 20.04.2 LTS
System Type | x86_64
Virtualization | Docker
Module | MinecraftModule
Loaded Plugins | FileManagerPlugin, EmailSenderPlugin, WebRequestPlugin, LocalFileBackupPlugin, CommonCorePlugin
Application Name | AMP
Application Version | 2.2.0.2
Release Stream | Release
Build Date | 26/07/2021 12:53
```

So far the Docker container has been working great, aside from something I think I'm missing. I've been using itzg/minecraft-server for a while and saw AMP as a way to consolidate all of my servers into an admin panel/runner. However, when I log into the AMP Panel, I only have the option to work with a single Minecraft Server. Do I need to run different instances of the image in my compose network to be able to use more than one? IE I have a vanilla, a Pixelmon, and a creative server, am I supposed to only have access to one server with this container?

If not, that's cool too, just didn't see an issue that mentioned this.

**Comment by kieeps** [comment]
When I log in to amp i get the option to create a bunch of instances, not sure why you would only be able to do one? 

Everytime I create a new instance it automatically get a unique port so that won't be a problem.

Don't you have the option to add more instances?

**Comment by MitchTalmadge** [comment]
I agree with above, it looks like you are using the "Minecraft" module. You should use "AMP". This will allow you to start multiple instances.

**Comment by judsonjames** [comment]
Yep, I must have overlooked that section entirely. I changed my module from `Minecraft` to `ADS`, deleted my `amp_data ` volume, rebuilt my container, and I was good to go. Now have several game servers running concurrently, after some configuration on some of the forge specific servers.

Thanks @kieeps, @MitchTalmadge
