### ISSUE TITLE
I cant connect via WinSCP

### ISSUE THREAD

**Issue by Ewj71** [MitchTalmadge/AMP-dockerized#86]
https://user-images.githubusercontent.com/69757318/130362120-d6721017-ea04-4ee3-bbb1-6e61fddad222.mp4

i cant connect so i cant upload why is this

**Comment by Ewj71** [comment]
![image](https://user-images.githubusercontent.com/69757318/130362510-953b0100-41d1-4f1e-b2e3-3150e88576cf.png)

**Comment by Dalarialus** [comment]
Have you forwarded the port through docker?

**Comment by MitchTalmadge** [comment]
I was able to reproduce the issue. Looking into it

**Comment by MitchTalmadge** [comment]
I got it working on mine!

1. Click the button in the File Manager to open the SFTP window:
![image](https://user-images.githubusercontent.com/8848080/141422491-a775a989-2897-4dd2-bffd-55aacd74d24b.png)

2. Take note of the port assigned:
![image](https://user-images.githubusercontent.com/8848080/141422688-4ee69cf5-1034-4305-9c92-59470bb1c3ed.png)

3. Forward the port in your Docker configuration. For example, if you use `docker-compose.yml`, it might look like this to open ports 2223 and 2224 (one is used for my ADS instance and one for my Minecraft instance)
![image](https://user-images.githubusercontent.com/8848080/141422917-a9b448dd-d86f-4dae-a52a-4ebf9b35d421.png)

4. Bring the container down and back up again.

5. Try it now!

If it's still not working, double check the `FileManagerPlugin.kvp` file inside your instance data folder. Look to make sure SFTP is enabled and the port is as expected. Also make sure it's bound to `0.0.0.0`. 

```
SFTP.SFTPEnabled=True
SFTP.SFTPPortNumber=2223
SFTP.SFTPIPBinding=0.0.0.0
```

Hopefully this helps some people. Please comment if you can't get it to work.
