### ISSUE TITLE
Feature Request:   ARM64/aarch builds

### ISSUE THREAD

**Issue by docgalaxyblock** [MitchTalmadge/AMP-dockerized#88]
At the moment I am upgrading to Proxmox 7.x and reworking some parts of my homlab.
I found you container and thought *that sounds like a good AMP controller*.
Then I realized there are currently no ARM64/aarch images

Now I like to give you a hint that a dockerized amp controller on a Raspberry Pi could be a good solution.
Also with the *current* development towards ARM on the part of Apple & more, ARM builds could become more interesting.

I think crossbuild should be possible through Github actions but I am not sure

Greetings 😉

**Comment by MitchTalmadge** [comment]
Hey I'd love to add support for this! Do you know of any resources for building aarch64 images with GH actions? I'll do some digging myself too.

**Comment by docgalaxyblock** [comment]
Hi, I have no clue but I found something this morning
https://www.youtube.com/watch?v=5yeeMdhGgrE

**Comment by MitchTalmadge** [comment]
I am trying to get this to work but the build is crashing while installing ca-certificates-mono:

https://github.com/MitchTalmadge/AMP-dockerized/runs/4149061530?check_suite_focus=true

**Comment by SahajJain01** [comment]
#108 I was able to successfully create and run an arm64 build with a modified dockerfile. 
There is an issue while amp instance is being created.

**Comment by rekonnected** [comment]
#140 should make it work completely, based on the work @SahajJain01 did in #108. I tested building and running both amd64 and arm64 images, both completely successful in my testing.

**Comment by AverageCakeSlice** [comment]
Late response, does this mean that we can get it to work on M1 MacOS hosts? I've got a Mac Mini that I'd like to use with AMP but they don't seem to have any distributions for MacOS.

**Comment by rekonnected** [comment]
#140 doesn't add any specific configuration for macOS hosts, but assuming docker running on M1 macOS identifies as or accepts "linux/arm64" which it seems to per [this link](https://medium.com/geekculture/docker-build-with-mac-m1-d668c802ab96), then it *should* work fine, though I haven't tested it on my M1P MBP yet. I'll see if I can test it out soon.

**Comment by MitchTalmadge** [comment]
Added AMD64 support to the latest release. Please test and open a new issue if something doesn't work. Thank you!
