### ISSUE TITLE
no java 16 which is necessary for minecraft 1.17

### ISSUE THREAD

**Issue by Pebkac03** [MitchTalmadge/AMP-dockerized#95]
As of 1.17 minecraft java edition servers require java 16 which the docker image dosen't seem to have as of now.

**Comment by MitchTalmadge** [comment]
The image has Java 16 but it's not the default yet. Go into the settings for the instance, Java section, and you can change it to 16

**Comment by Pebkac03** [comment]
Dosen't show up, also checked the usr/lib/jvm dir. Running v2.2.1.

**Comment by Pebkac03** [comment]
fixed, for some reason "Latest" tag was not working when running using trueNAS scale's built in docker GUI. had to use the tag specific to the newest version.
