### ISSUE TITLE
AMP Minecraft-Instance no longer listening for game-port

### ISSUE THREAD

**Issue by Ting3l** [MitchTalmadge/AMP-dockerized#96]
Hi,

I set up a minecraft-instance like a week or two ago.
At first it ran like a charm, but today I notice I'm no longer able to connect.
Some troubleshooting and testing later:

AMP/Minecraft is not opening the port to listen for connections.
Minecraft log looks fine, though, server starting as usual and telling the right port he'll listen to.
Doing "ampinstmgr ports instancename" inside the container returns the following:

amp@2a664b20a63f:~$ ampinstmgr ports Minecraft
[Info] AMP Instance Manager v2.2.2.2 built 18/10/2021 14:39
[Info] Release spec: Release - built by CUBECODERS/buildbot on CCL-DEV
[Info] Port usage for Minecraft (Minecraft)
[Info] Instance is currently running.
[Info] LISTENING        8081    TCP     (Core.Webserver.Port)

That's it. It's missing the Minecraft-port 25565.
Changing the port (to 25566 and 25567) as well as multiple reboots (Instance, container & host) didn't fix this. Any ideas on what I can do?
I haven't played in afew days, so honestly I suspect the version/update from 18/10/21 to be the problem?
Do I simply need to re-deploy in a new container with a previous version?
If so, any ideas on what happened?

**Comment by Joly0** [comment]
Is this still an issue? If so, you could try starting the container, docker exec into it, log in as the amp user and run this command "ampinstmgr --nocache upgradeall"
Afterwards you could try to set the port for minecraft again via ads (if you have that setup) or via console with the help of the "ampinstmgr --RebindInstance" command

**Comment by Ting3l** [comment]
Actually I solved it by doing a full re-deployment und configuration until everything workes as expected.

However a friend of mine still hast the problem after multiple re-installs, but he is running AMP without the Docker-layer, so he will open a ticket in den main AMP-github.

 

Thanks though, I guess this case can be closed as I solved my initial problem and the root cause doesn't seem to be due to docker.

 
 

Gesendet: Dienstag, 09. November 2021 um 21:47 Uhr
Von: "Joly0" ***@***.***>
An: "MitchTalmadge/AMP-dockerized" ***@***.***>
Cc: "Ting3l" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [MitchTalmadge/AMP-dockerized] AMP Minecraft-Instance no longer listening for game-port (Issue #96)


 

Is this still an issue? If so, you could try starting the container, docker exec into it, log in as the amp user and run this command "ampinstmgr --nocache upgradeall"
Afterwards you could try to set the port for minecraft again via ads (if you have that setup) or via console with the help of the "ampinstmgr --RebindInstance" command

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rbretmounet** [comment]
> Actually I solved it by doing a full re-deployment und configuration until everything workes as expected. However a friend of mine still hast the problem after multiple re-installs, but he is running AMP without the Docker-layer, so he will open a ticket in den main AMP-github.   Thanks though, I guess this case can be closed as I solved my initial problem and the root cause doesn't seem to be due to docker.     Gesendet: Dienstag, 09. November 2021 um 21:47 Uhr Von: "Joly0" ***@***.***> An: "MitchTalmadge/AMP-dockerized" ***@***.***> Cc: "Ting3l" ***@***.***>, "Author" ***@***.***> Betreff: Re: [MitchTalmadge/AMP-dockerized] AMP Minecraft-Instance no longer listening for game-port (Issue #96)   Is this still an issue? If so, you could try starting the container, docker exec into it, log in as the amp user and run this command "ampinstmgr --nocache upgradeall" Afterwards you could try to set the port for minecraft again via ads (if you have that setup) or via console with the help of the "ampinstmgr --RebindInstance" command — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Did your friend ever solve this issue?
