### ISSUE TITLE
Truenas Scale

### ISSUE THREAD

**Issue by IsmaStifler** [MitchTalmadge/AMP-dockerized#98]
Hi, I am trying to deploy the docker image in Truenas Scale and it is impossible, it gives me an error when starting the image, could someone help me, a small tutorial? Thanks

**Comment by Joly0** [comment]
Hey, if you say you get an error message, would you mind sharing this with us so we can identify what the problem is and maybe help you with your problem?

**Comment by IsmaStifler** [comment]
Basically in the truenas scale docker, it doesn't start, I can't access the configuration portal, it doesn't start, what do u need?

**Comment by IsmaStifler** [comment]
Stay deploying

**Comment by Joly0** [comment]
Some screenshots would help i guess

**Comment by IsmaStifler** [comment]
I Send of all or some specific part?

**Comment by Joly0** [comment]
Anything that could help identify your issue

**Comment by IsmaStifler** [comment]
Ok, I just installed the docker again, with different values and different settings so you can see how

upload screenshot

**Comment by IsmaStifler** [comment]
![1](https://user-images.githubusercontent.com/19431908/141004565-b6d9ce90-de72-4bf5-98e1-77c1bf473ca9.png)
![2](https://user-images.githubusercontent.com/19431908/141004576-c3e638e5-dce4-406f-a747-88c86143acb8.png)
![3](https://user-images.githubusercontent.com/19431908/141004577-9a6310a1-cca6-4594-a808-8cae27295236.png)
![4](https://user-images.githubusercontent.com/19431908/141004584-4ccca8a9-7866-4c1d-8b3f-a0aabbebf68f.png)
![5](https://user-images.githubusercontent.com/19431908/141004589-73b1d7d9-2f9a-416e-8371-4119fe456ccf.png)

![6](https://user-images.githubusercontent.com/19431908/141004595-f1378021-d35e-4252-b8b6-75cde13e7564.png)
![7](https://user-images.githubusercontent.com/19431908/141004602-9c7fdbf6-deaa-4018-a145-a7d45c7adf41.png)
![8](https://user-images.githubusercontent.com/19431908/141004607-78a0362c-611c-4711-a8d8-44cac0d3d501.png)

![9](https://user-images.githubusercontent.com/19431908/141004616-576ed266-1501-43c2-8084-ea5cb4f1d7ce.png)
![10](https://user-images.githubusercontent.com/19431908/141004622-28a711fb-3a09-49a1-a04d-e18e3c7ae466.png)

**Comment by MitchTalmadge** [comment]
You haven't set any environment variables (at minimum you need LICENCE) and you have used the wrong volumes (the container volume should be at `/home/amp/.ampdata`). Please look at the README in detail.

**Comment by Joly0** [comment]
You have to set some environment variables

**Comment by IsmaStifler** [comment]
Would there be any way to add the repository and then add the LICENSE? and that it was directly installed as one more app?

**Comment by IsmaStifler** [comment]
![1](https://user-images.githubusercontent.com/19431908/141009012-8b5d25d3-0728-4137-beb0-eb3b29497242.png)
![2](https://user-images.githubusercontent.com/19431908/141009015-c1b0eb56-2bc3-4ea7-aa54-772897d1f363.png)

**Comment by IsmaStifler** [comment]
> You haven't set any environment variables (at minimum you need `LICENCE`) and you have used the wrong volumes (the container volume should be at `/home/amp/.ampdata`). Please look at the README in detail.

`Error: [EFAULT] Failed to create dataset: Pool not found`

sorry for being a rookie

**Comment by IsmaStifler** [comment]
![1](https://user-images.githubusercontent.com/19431908/141012863-96461782-b07d-4852-9ff4-58f1ded8b827.png)

**Comment by IsmaStifler** [comment]
![1](https://user-images.githubusercontent.com/19431908/141013265-b6b6eeed-ff04-4763-bfad-c360ce3b1478.png)
ok perfect already works, but how do I start the record? ; (

**Comment by Joly0** [comment]
I guess this can get closed then?

**Comment by IsmaStifler** [comment]
> I guess this can get closed then?

yes, the only thing that I can't configure where the games are saved? for example of the satisfactory

**Comment by Joly0** [comment]
The games are saved in your volume in various subfolders according to the name you give the instances through ads

**Comment by IsmaStifler** [comment]
> Los juegos se guardan en su volumen en varias subcarpetas de acuerdo con el nombre que le da a las instancias a través de anuncios.

if you thought so, for example the items of the satisfactory should be in intances> main folder name, but there it is not saved

**Comment by Joly0** [comment]
> > Los juegos se guardan en su volumen en varias subcarpetas de acuerdo con el nombre que le da a las instancias a través de anuncios.
> 
> if you thought so, for example the items of the satisfactory should be in intances> main folder name, but there it is not saved

The files are under ampdata/instances/ and then inside a folder named after your instance

**Comment by Joly0** [comment]
But if you are unsure, you can send usna screenshot of the files insode the instances folder

**Comment by IsmaStifler** [comment]
for instance
the games saved locally in the game leave in this direction
C:\Users\username\AppData\Local\FactoryGame\Saved\SaveGames\steam id

Or for example on a win 19 server the path of the saved games are here.

C:\Windows\ServiceProfiles\NetworkService\AppData\Local\FactoryGame\Saved\SaveGames\server

That is why in instances this folder does not appear within the name of the game, add that I set amp to run and save locally

**Comment by IsmaStifler** [comment]
> But if you are unsure, you can send usna screenshot of the files insode the instances folder
![Sin título](https://user-images.githubusercontent.com/19431908/141599992-e896a0de-7f2f-41c1-a2e2-5c25e7554080.png)

**Comment by Joly0** [comment]
I can definitly tell you, that somewhere in a subfolder there are the save games, though this is neither an option for us to define a location nor for amp itself, this is up to the game dev. So we cant help you find the save games, but we can tell you, that they are definitly there

**Comment by outpoints** [comment]
> ![1](https://user-images.githubusercontent.com/19431908/141013265-b6b6eeed-ff04-4763-bfad-c360ce3b1478.png) ok perfect already works, but how do I start the record? ; (
> 
> edit:
> 
> ```
> admin
> password
> ```
> 
> all perfect nice
> 
> thx!!

What port did you connect to it from once you solved your issues?
I've been unable to access the web interface no matter what port I've tried to use. Even using your ports of 4000 and 39000 I can't access it.
I'd appreciate if you could share what you did! Thanks!

**Comment by MitchTalmadge** [comment]
> What port did you connect to it from once you solved your issues? I've been unable to access the web interface no matter what port I've tried to use. Even using your ports of 4000 and 39000 I can't access it. I'd appreciate if you could share what you did! Thanks!

The default port is `8080`, make sure it is forwarded wherever your container config is.
